---
# Check if the kernel supports KSM advisor mode (newer kernels)
- name: Check if KSM advisor mode is supported
  stat:
    path: /sys/kernel/mm/ksm/advisor_mode
  register: ksm_advisor_mode

- name: Configure KSM to run on boot (with advisor)
  copy:
    content: |
      w /sys/kernel/mm/ksm/run - - - - 1
      w /sys/kernel/mm/ksm/advisor_mode - - - - scan-time
      w /sys/kernel/mm/ksm/merge_across_nodes - - - - 0
      w /sys/kernel/mm/ksm/advisor_target_scan_time - - - - 60
    dest: /etc/tmpfiles.d/sf-ksm.conf
    owner: root
    mode: ugo+r
  when: ksm_enabled == "1" and ksm_advisor_mode.stat.exists

- name: Configure KSM to run on boot (without advisor)
  copy:
    content: |
      w /sys/kernel/mm/ksm/run - - - - 1
      w /sys/kernel/mm/ksm/pages_to_scan - - - - 1000000
      w /sys/kernel/mm/ksm/merge_across_nodes - - - - 0
    dest: /etc/tmpfiles.d/sf-ksm.conf
    owner: root
    mode: ugo+r
  when: ksm_enabled == "1" and not ksm_advisor_mode.stat.exists

# merge_across_nodes requires a reboot, so is skipped below
- name: Configure KSM to run now (with advisor)
  shell: |
    echo "1" > /sys/kernel/mm/ksm/run
    echo "scan-time" > /sys/kernel/mm/ksm/advisor_mode
    echo 60 > /sys/kernel/mm/ksm/advisor_target_scan_time
  ignore_errors: True
  when: ksm_enabled == "1" and ksm_advisor_mode.stat.exists

- name: Configure KSM to run now (without advisor)
  shell: |
    echo "1" > /sys/kernel/mm/ksm/run
    echo "1000000" > /sys/kernel/mm/ksm/pages_to_scan
  ignore_errors: True
  when: ksm_enabled == "1" and not ksm_advisor_mode.stat.exists

- name: Configure KSM to not run on boot
  copy:
    content: |
      w /sys/kernel/mm/ksm/run - - - - 0
      w /sys/kernel/mm/ksm/advisor_mode - - - - none
      w /sys/kernel/mm/ksm/merge_across_nodes - - - - 0
    dest: /etc/tmpfiles.d/sf-ksm.conf
    owner: root
    mode: ugo+r
  when: ksm_enabled != "1"

# merge_across_nodes requires a reboot, so is skipped below
- name: Configure KSM to not run now
  shell: |
    echo "0" > /sys/kernel/mm/ksm/run
    echo "none" > /sys/kernel/mm/ksm/advisor_mode
  ignore_errors: True
  when: ksm_enabled != "1"