# We cannot do this in the shaken fist network configuration because
# cloud-init will randomly use the mesh interface as the default route
# which breaks networking. So we configure this interface after cloud-init
# has run. We also need to specify the MTU manually here because we're not
# fetching it from dhcp any more.
- name: Configure the mesh interface (Debian)
  copy:
    content: |
      auto eth1
      iface eth1 inet static
        mtu 8950
        address {{mesh_ip}}/24
    dest: /etc/network/interfaces.d/60-sf-mesh-net
    owner: root
    group: root
    mode: u=r,g=r,o=r
  when: ansible_distribution == 'Debian'

# This is a bit terrible. We're doing two things here (not in order): we're
# configuring the mesh network interface (eth1), but we're also arguing with
# ifup / systemd networking about eth0 and whether DHCP leases should be
# renewed. I think this is papering over a negative interaction between
# debian and cloud-init, but I am not entirely sure what the issue is here.
- name: Enable networking (Debian)
  shell: |
    ifup --ignore-errors eth0

    orig=$(ip -o link | grep {{mesh_mac}} | cut -f 2 -d ":")
    if [ ${orig} != "eth1" ]; then
      ip link set down ${orig}
      ip link set ${orig} name eth1
    fi

    ifup --ignore-errors eth1

    systemctl restart networking
  when: ansible_distribution == 'Debian'

- name: Configure the mesh interface (Ubuntu)
  template:
    src: files/netplan-eth1.yaml
    dest: /etc/netplan/99-sfci.yaml
  vars:
    address: "{{mesh_ip}}/24"
    macaddr: "{{mesh_mac}}"
  when: ansible_distribution == 'Ubuntu'

- name: Enable eth1 (Ubuntu)
  shell: netplan apply
  when: ansible_distribution == 'Ubuntu'
