- name: Disable logrotate
  service:
    name: logrotate
    enabled: no
    state: stopped

- name: Disable logrotate.timer
  service:
    name: logrotate.timer
    enabled: no
    state: stopped

- name: Use CI package cache to speed things up
  copy:
    content: |
      Acquire::http::Proxy "http://192.168.1.50:8000";
    dest: /etc/apt/apt.conf.d/00proxy
    owner: root
    group: root
    mode: u=r,g=r,o=r

- name: Copy server wheel file
  copy:
    src: "{{source_path}}/shakenfist/dist/{{hostvars['localhost']['server_wheel_file']}}"
    dest: "/tmp/{{hostvars['localhost']['server_wheel_file']}}"
