- hosts: localhost
  gather_facts: yes
  connection: ssh
  vars:
    identifier: unknown
    source_path: "/home/jenkins/src/shakenfist/"
    base_image: "https://sfcbr.shakenfist.com/static/ubuntu2004-ci-template.qcow2"
    base_image_user: "ubuntu"

  tasks:
    - include_tasks: ci-include-multinode-localhost.yml
    - include_tasks: ci-include-common-localhost.yml

- hosts: sfall
  gather_facts: yes
  become: true
  vars:
    source_path: "/home/jenkins/src/shakenfist/"

  tasks:
    - include_tasks: ci-include-common-sfnodes.yml
    - include_tasks: ci-include-multinode-sfnodes.yml

- hosts: primary
  gather_facts: yes
  connection: ssh
  become: true

  tasks:
    - include_tasks: ci-include-common-primary.yml

    - name: Create a RAM disk for etcd to make it more reliable in CI
      shell: |
        mkdir -p /var/lib/etcd
        mount -t tmpfs -o rw,size=2G tmpfs /var/lib/etcd

    - name: Copy getsf
      copy:
        src: "{{source_path}}/shakenfist/deploy/getsf"
        dest: "/tmp/getsf"
        mode: ugo+rwx

    - name: Write a simple getsf wrapper
      copy:
        content: |
          export GETSF_FLOATING_BLOCK=192.168.230.0/24
          export GETSF_DEPLOY_NAME=bonkerslab
          export GETSF_RELEASE=local
          export GETSF_LOCAL_SOURCE=static
          export GETSF_WARNING=yes

          export GETSF_SERVER_PACKAGE="/root/{{hostvars['localhost']['server_wheel_file']}}"
          export GETSF_CLIENT_PACKAGE="/root/{{hostvars['localhost']['client_wheel_file']}}"

          export GETSF_NODES="sf-primary sf-1 sf-2 sf-3 sf-4 sf-5"
          export GETSF_SSH_USER="{{base_image_user}}"
          export GETSF_SSH_KEY_FILENAME="/root/.ssh/id_rsa"
          export GETSF_NODE_PRIMARY="sf-primary"
          export GETSF_NODE_NETWORK="sf-1"
          export GETSF_NODE_EVENTLOG="sf-primary"
          export GETSF_NODE_ETCD_MASTER="sf-primary"
          export GETSF_NODE_STORAGE=""
          export GETSF_NODE_HYPERVISOR="sf-1 sf-2 sf-3 sf-4 sf-5"

          export GETSF_NODE_EGRESS_NIC_sf_primary="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_primary="{{hostvars['primary']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_primary="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_primary="{{hostvars['primary']['mesh_ip']}}"

          export GETSF_NODE_EGRESS_NIC_sf_1="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_1="{{hostvars['sf1']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_1="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_1="{{hostvars['sf1']['mesh_ip']}}"

          export GETSF_NODE_EGRESS_NIC_sf_2="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_2="{{hostvars['sf2']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_2="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_2="{{hostvars['sf2']['mesh_ip']}}"

          export GETSF_NODE_EGRESS_NIC_sf_3="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_3="{{hostvars['sf3']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_3="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_3="{{hostvars['sf3']['mesh_ip']}}"

          export GETSF_NODE_EGRESS_NIC_sf_4="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_4="{{hostvars['sf4']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_4="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_4="{{hostvars['sf4']['mesh_ip']}}"

          export GETSF_NODE_EGRESS_NIC_sf_5="eth0"
          export GETSF_NODE_EGRESS_ADDRESS_sf_5="{{hostvars['sf5']['egress_ip']}}"
          export GETSF_NODE_MESH_NIC_sf_5="eth1"
          export GETSF_NODE_MESH_ADDRESS_sf_5="{{hostvars['sf5']['mesh_ip']}}"

          export GETSF_SKIP_COMMON_IMAGES=1

          sudo --preserve-env /tmp/getsf
        dest: "/tmp/getsf-wrapper"
        mode: ugo+rwx
