[metadata]
name = shakenfist
summary = Shaken Fist: an opinionated minimal cloud
license = Apache2
description-file = README.md
author = Michael Still
author_email = mikal@stillhq.com
home_page = https://madebymikal.com/shakenfist
classifier =
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3.9

[files]
packages =
    shakenfist

[entry_points]
console_scripts =
    sf-ctl = shakenfist.client.ctl:cli
    sf-backup = shakenfist.client.backup:cli

    sf-api = shakenfist.daemons.external_api.main:main
    sf-cleaner = shakenfist.daemons.cleaner.main:main
    sf-cluster = shakenfist.daemons.cluster.main:main
    sf-eventlog = shakenfist.daemons.eventlog.main:main
    sf-net = shakenfist.daemons.network.main:main
    sf-queues = shakenfist.daemons.queues.main:main
    sf-resources = shakenfist.daemons.resources.main:main
    sf-sentinel-first = shakenfist.daemons.sentinel_first.main:main
    sf-sentinel-last = shakenfist.daemons.sentinel_last.main:main
    sf-sidechannel = shakenfist.daemons.sidechannel.main:main
    sf-transfers = shakenfist.daemons.transfers.main:main

    sf-privexec = shakenfist.daemons.privexec.main:main
    sf-nodelock = shakenfist.daemons.nodelock.main:main

[pbr]
skip_changelog = True
