# grafana
deploy_name: "sf"
system_key: "unknown"

# cluster_config
database_node_ip: "127.0.0.1"
auth_secret: "unknown"
ram_system_reservation: 5
lowest_mtu: 1500
dns_server: "8.8.8.8"
http_proxy: ""
extra_config: "{{ extra_config }}"