---
- debug:
    msg:
      - "Managing host certificate for {{ hostname }}."
      - "CA cert path: {{ ca_cert_path }}"
      - "CA key path: {{ ca_key_path }}"
      - "CA template path: {{ ca_template_path }}"
      - "Host cert path: {{ host_cert_path }}"
      - "Host key path: {{ host_key_path }}"
      - "Host template path: {{ host_template_path }}"

- name: Check if the host certificate is already created
  stat:
    path: /etc/pki/libvirt-spice/server_cert.pem
  register: host_cert

- name: Check certificate lifetime
  shell: |
    openssl x509 -checkend $(( 3600 * 24 * 30 )) -noout \
        -in /etc/pki/libvirt-spice/server_cert.pem || true
  register: host_cert_expires
  when: host_cert.stat.exists

- name: Log certificate expiry result
  debug:
    msg: "{{ host_cert_expires }}"
  when: host_cert.stat.exists

- name: Move aside old certificate
  shell:
    mv "{{ host_cert_path }}" "{{ host_key_path }}".$(date +%Y%m%d)".pem"
  delegate_to: local
  delegate_facts: true
  when: host_cert.stat.exists and not host_cert_expires.meta.stdout == "Certificate will expire"

- name: Check if the host certificate still exists
  stat:
    path: "{{ host_cert_path }}"
  delegate_to: local
  delegate_facts: true
  register: host_cert

- name: Check if the host key exists
  stat:
    path: "{{ host_key_path }}"
  delegate_to: local
  delegate_facts: true
  register: host_key

- name: Write host certificate template
  copy:
    content: |
      organization = Shaken Fist CA for {{deploy_name}}
      cn = {{ hostname }}
      tls_www_server
      encryption_key
      signing_key
    dest: "{{ host_template_path }}"
    owner: root
    mode: u=r
  delegate_to: local
  delegate_facts: true
  when: not host_cert.stat.exists

- name: Create host key
  shell:
    umask 277 && certtool --generate-privkey > "{{ host_key_path }}"
  delegate_to: local
  delegate_facts: true
  when: not host_key.stat.exists

- name: Create host certificate
  shell:
    certtool --generate-certificate \
      --template "{{ host_template_path }}" \
      --load-privkey "{{ host_key_path }}" \
      --load-ca-certificate "{{ ca_cert_path }}" \
      --load-ca-privkey "{{ ca_key_path }}" \
      --outfile "{{ host_cert_path }}"
  delegate_to: local
  delegate_facts: true
  when: not host_cert.stat.exists