#!/usr/bin/python3
import datetime
import fcntl
import json
import os
import secrets
import select
import string
import subprocess
import sys


PASSWORD_CHARS = ''
for c in string.ascii_letters + string.ascii_letters.upper() + string.digits:
    PASSWORD_CHARS += c


def generate_hosts_file(topology, ssh_user, ssh_key_filename):
    """Generate Ansible inventory from topology with group membership.

    This generates the hosts file before ansible runs, so all groups are
    populated at parse time. This avoids issues with dynamic inventory via
    add_host where plays targeting dynamically-created groups are skipped
    because groups are empty at playbook parse time.

    Note: Only SSH connection variables are set in the hosts file. Node-specific
    variables (node_name, node_mesh_ip, etc.) are set via set_fact in deploy.yml
    to avoid template recursion issues when the hostname matches a variable value.
    """
    lines = [
        '# Generated by deploy.py from topology',
        '# Do not edit manually - regenerated on each deploy',
        '',
        '[local]',
        'localhost ansible_connection=local',
        '',
    ]

    # Group definitions - collect nodes by group
    groups = {
        'primary_node': [],
        'network_node': [],
        'hypervisors': [],
        'etcd_master': [],
        'storage': [],
    }

    topology_data = json.loads(topology)

    # Build group membership
    for node in topology_data:
        name = node['name']
        if node.get('primary_node', False):
            groups['primary_node'].append(name)
        if node.get('network_node', False):
            groups['network_node'].append(name)
        if node.get('hypervisor', False):
            groups['hypervisors'].append(name)
        if node.get('etcd_master', False):
            groups['etcd_master'].append(name)
        if node.get('storage', False):
            groups['storage'].append(name)

    # Build node lookup for host vars
    node_lookup = {n['name']: n for n in topology_data}

    # Helper to format host entry with SSH connection variables only.
    # Node-specific variables (node_name, node_mesh_ip, etc.) are set via
    # set_fact in deploy.yml to avoid template recursion issues that occur
    # when the hostname matches a variable value (e.g., node_name=localhost
    # on a host named localhost).
    def format_host_entry(name):
        node = node_lookup[name]
        parts = [
            name,
            f"ansible_ssh_host={node['node_egress_ip']}",
            f'ansible_ssh_user={ssh_user}',
            f'ansible_ssh_private_key_file={ssh_key_filename}',
            f'ansible_fqdn={name}',
        ]
        return ' '.join(parts)

    # Write each group with host variables
    for group_name in ['primary_node', 'network_node',
                       'hypervisors', 'etcd_master', 'storage']:
        lines.append(f'[{group_name}]')
        seen = set()  # Avoid duplicate entries within same group
        for name in groups[group_name]:
            if name not in seen:
                lines.append(format_host_entry(name))
                seen.add(name)
        lines.append('')

    # allsf group as children of other groups
    lines.extend([
        '[allsf:children]',
        'primary_node',
        'network_node',
        'hypervisors',
        'etcd_master',
        'storage',
        '',
        '[allsf:vars]',
        "ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
        "ansible_python_interpreter='/usr/bin/python3'",
        '',
    ])

    return '\n'.join(lines)


os.makedirs('/etc/sf', exist_ok=True)
with open('/etc/sf/deploy-log', 'w') as logfile:
    def log_write(s):
        s = s.rstrip()
        timestamp = datetime.datetime.now()
        print(f'{timestamp} {s}')
        logfile.write(f'{timestamp} {s.rstrip()}\n')

    variables = {}
    if os.path.exists('/etc/sf/deploy-vars.json'):
        with open('/etc/sf/deploy-vars.json') as varsfile:
            variables = json.loads(varsfile.read())

    def update_if_specified(varname, default, rename=None):
        v = os.environ.get(varname.upper())
        if rename:
            varname = rename

        if v:
            variables[varname] = v
            log_write(f'Changed configuration value {varname} to {v}')
        elif varname not in variables:
            variables[varname] = default
            log_write(f'Defaulted configuration value {varname} to {v}')

    def update_if_specified_bool(varname, default):
        v = os.environ.get(varname.upper())
        if v:
            if v.lower() == 'true':
                v = '1'
            elif v.lower() == 'false':
                v = '0'
            variables[varname] = v
            log_write(f'Changed configuration value {varname} to {v}')
        elif varname not in variables:
            variables[varname] = default
            log_write(f'Defaulted configuration value {varname} to {v}')

    update_if_specified('server_package', 'shakenfist')
    update_if_specified('client_package', 'shakenfist-client')
    update_if_specified('agent_package', 'shakenfist-agent')
    update_if_specified('pip_extra', '')
    update_if_specified('topology', None)

    update_if_specified('ssh_key_filename', '')
    if variables['ssh_key_filename'] and os.path.exists(variables['ssh_key_filename']):
        with open(variables['ssh_key_filename']) as f:
            variables['ssh_key'] = f.read()
    update_if_specified('ssh_user', '')

    update_if_specified(
        'admin_password', ''.join(secrets.choice(PASSWORD_CHARS) for i in range(12)))
    update_if_specified(
        'auth_secret', ''.join(secrets.choice(PASSWORD_CHARS) for i in range(50)))
    update_if_specified(
        'mariadb_password', ''.join(secrets.choice(PASSWORD_CHARS) for i in range(24)))

    # vault_system_key_path must be absent not empty if unset
    update_if_specified('vault_system_key_path', '')
    if variables['vault_system_key_path'] == '':
        del variables['vault_system_key_path']

    update_if_specified('floating_ip_block', '10.10.0.0/24', rename='floating_network_ipblock')
    update_if_specified_bool('ksm_enabled', '1')
    update_if_specified('deploy_name', 'sf')
    update_if_specified_bool('ignore_mtu', '0')
    update_if_specified('dns_server', '8.8.8.8')
    update_if_specified('http_proxy', '')

    update_if_specified('extra_config', '[]')

    with open('/etc/sf/deploy-vars.json', 'w') as varsfile:
        varsfile.write(json.dumps(variables, indent=4, sort_keys=True))

    log_write('Install started')
    log_write('Install variables:\n    %s'
              % '\n    '.join(json.dumps(variables, indent=4, sort_keys=True).split('\n')))

    # Generate hosts file from topology if available
    if variables.get('topology'):
        hosts_content = generate_hosts_file(
            variables['topology'],
            variables.get('ssh_user', ''),
            variables.get('ssh_key_filename', '')
        )
        hosts_path = '/etc/sf/ansible-hosts'
        with open(hosts_path, 'w') as f:
            f.write(hosts_content)
        log_write(f'Generated Ansible hosts file at {hosts_path}')
    else:
        # Fallback to static file for local testing without topology
        hosts_path = 'hosts'
        log_write('No topology provided, using static hosts file')

    env = os.environ.copy()
    env['ANSIBLE_SSH_PIPELINING'] = '0'

    obj = subprocess.Popen(
        (f'ansible-playbook -i {hosts_path} --extra-vars "@/etc/sf/deploy-vars.json" '
         f'{" ".join(sys.argv[1:])} deploy.yml'),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=True,
        env=env)
    log_write('Installer pid is %d\n' % obj.pid)

    flags = fcntl.fcntl(obj.stdout, fcntl.F_GETFL)
    fcntl.fcntl(obj.stdout, fcntl.F_SETFL, flags | os.O_NONBLOCK)

    flags = fcntl.fcntl(obj.stderr, fcntl.F_GETFL)
    fcntl.fcntl(obj.stderr, fcntl.F_SETFL, flags | os.O_NONBLOCK)

    obj.stdin.close()
    while obj.poll() is None:
        readable, _, _ = select.select([obj.stderr, obj.stdout], [], [], 1)
        for f in readable:
            d = os.read(f.fileno(), 10000)
            for line in d.decode('utf-8').split('\n'):
                log_write(line)

    log_write('\nInstall finished with exit code %d' % obj.returncode)

    if obj.returncode != 0:
        log_write('***************************************************')
        log_write('*                     WARNING                     *')
        log_write('*                                                 *')
        log_write('* The return code of the deploy script indicates  *')
        log_write('* that your install has failed. You will need to  *')
        log_write('* inspect /etc/sf/deploy-log to determine why.    *')
        log_write('* The failure will likely look like a fatal       *')
        log_write('* ansible task. You can also request assistance   *')
        log_write('* by filing a github issue at                     *')
        log_write('* https://github.com/shakenfist/shakenfist/issues *')
        log_write('***************************************************')
        sys.exit(obj.returncode)

    # Reset any previously failed systemd units so we notice if we cause
    # failures. We deliberately ignore the return code here because its
    # just a preventative measure.
    subprocess.Popen('systemctl reset-failed', shell=True)
    sys.exit(0)
