# Fake terraform for hard coded metal

- name: Add sf-1 to ansible
  add_host:
    hostname: sf-1
    ansible_ssh_host: "{{metal_ip_sf1}}"
    groups: hypervisors, etcd_master

- name: Add sf-1 node_ip
  set_fact:
    node_name: "sf-1"
    node_ip: "{{metal_ip_sf1}}"
  delegate_to: sf-1
  delegate_facts: true

- name: Add sf-2 to ansible
  add_host:
    hostname: sf-2
    ansible_ssh_host: "{{metal_ip_sf2}}"
    groups: hypervisors, etcd_master

- name: Add sf-2 node_ip
  set_fact:
    node_name: "sf-2"
    node_ip: "{{metal_ip_sf2}}"
  delegate_to: sf-2
  delegate_facts: true

- name: Add sf-3 to ansible
  add_host:
    hostname: sf-3
    ansible_ssh_host: "{{metal_ip_sf3}}"
    groups: hypervisors, etcd_master

- name: Add sf-3 node_ip
  set_fact:
    node_name: "sf-3"
    node_ip: "{{metal_ip_sf3}}"
  delegate_to: sf-3
  delegate_facts: true

- name: Log terraform hosts
  debug:
    msg:
      - "sf-1: {{hostvars['sf-1']['ansible_ssh_host']}}, {{hostvars['sf-1']['node_ip']}}"
      - "sf-2: {{hostvars['sf-2']['ansible_ssh_host']}}, {{hostvars['sf-2']['node_ip']}}"
      - "sf-3: {{hostvars['sf-3']['ansible_ssh_host']}}, {{hostvars['sf-3']['node_ip']}}"
