- name: Setup /etc/hosts
  copy:
    content: |
      127.0.0.1 localhost

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

      {% for svr in groups.hypervisors %}
      {{hostvars[svr]['node_ip']}}  {{svr}}
      {% endfor %}
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=r,g=r,o=r

- name: Determine network node
  set_fact:
    network_node_ip: "{{hostvars['sf-1']['node_ip']}}"
  delegate_to: localhost
  delegate_facts: true
