- name: Deploy infrastructure
  terraform:
    project_path: "{{ansible_root}}/terraform/gcp"
    state: present
    force_init: true
    variables:
      project: "{{project}}"
      uniqifier: "{{uniqifier}}"
      ssh_user: "{{ssh_user}}"
      ssh_key: "{{ssh_key}}"
      node_count: "{{node_count}}"
      node_image: "{{node_image}}"
  register: terraform_out

- name: Determine node_ip for the primary node
  shell: ip addr | grep "inet 10" | sed -e 's/.*inet //' -e 's/\/32.*//'
  register: primary_ip_complex
  ignore_errors: True

- name: Set primary node_ip
  set_fact:
    node_ip: "{{primary_ip_complex.stdout}}"
    primary_node_ip: "{{primary_ip_complex.stdout}}"
  delegate_to: localhost
  delegate_facts: true

- name: Add sf nodes
  add_host:
    hostname: "sf-{{node_idx + 1}}"
    node_name: "sf-{{node_idx + 1}}"
    ansible_ssh_host: "{{item}}"
    ansible_ssh_user: "{{ssh_user}}"
    ansible_ssh_private_key_file: "{{ssh_key_filename|default(omit)}}"
    groups: hypervisors
  loop: "{{terraform_out.outputs.sf_nodes_external_ip.value}}"
  loop_control:
    index_var: node_idx

- name: Add sf nodes internal IPs
  set_fact:
    node_ip: "{{item}}"
  delegate_to: "sf-{{node_idx + 1}}"
  delegate_facts: true
  loop: "{{terraform_out.outputs.sf_nodes_internal_ip.value}}"
  loop_control:
    index_var: node_idx

- name: Add sf-1 as an etcd master
  add_host:
    hostname: "sf-1"
    groups: hypervisors, etcd_master

- name: Add sf-2 as an etcd master
  add_host:
    hostname: "sf-2"
    groups: hypervisors, etcd_master

- name: Add sf-3 as an etcd master
  add_host:
    hostname: "sf-3"
    groups: hypervisors, etcd_master
