{
 "title": "Shaken Fist",
 "tags": [ "shakenfist" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_load_5", "legendFormat": "{{instance}} loadavg 5" }
   ]
  },
  {
   "title": "Instance vCPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_total_instance_vcpus", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instance CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_total_instance_cpu_time[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "memory_max", "legendFormat": "{{instance}} max" }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "memory_available", "legendFormat": "{{instance}} available" }
   ]
  },
  {
   "title": "Instance memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_total_instance_actual_memory",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "disk_free", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instances total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instances_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}