syntax = "proto3";

package shakenfist.protos;

service EventService {
  rpc RecordEvent (EventRequest) returns (EventReply) {}
  rpc RecordMultiEvent (EventMultiRequest) returns (EventReply) {}
}

// An event against a single object, should be removed one day
message EventRequest {
    string object_type = 1;
    string object_uuid = 2;
    string event_type = 3;
    optional float obsolete_timestamp = 4;
    string fqdn = 5;
    float duration = 6;
    string message = 7;
    string extra = 8;
    double timestamp = 9;
}

// An event against multiple objects
message EventObject {
  string object_type = 1;
  string object_uuid = 2;
}

message EventMultiRequest {
  repeated EventObject objects = 1;
  string event_type = 2;
  string fqdn = 3;
  float duration = 4;
  string message = 5;
  string extra = 6;
  double timestamp = 7;
}

// An ack from the eventlog daemon
message EventReply {
  bool ack = 1;
}