apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  orgId: 1
  url: http://{{node_mesh_ip}}:9090
  isDefault: true
  version: 1
  editable: false
  access: proxy
  jsonData:
    tlsSkipVerify: true