global:
  external_labels:
    monitor: 'shakenfist'
    origin_prometheus: {{ deploy_name }}

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [
            {% for svr in groups.allsf %}
              '{{hostvars[svr]['node_name']}}:9100',
            {% endfor %}
          ]
  - job_name: 'shakenfist'
    static_configs:
      - targets: [
            {% for svr in groups.sf_prometheus_exporters %}
              '{{hostvars[svr]['node_name']}}:13001',
            {% endfor %}
          ]
      # metric_relabel_configs:
      # - source_labels: [__name__]
      #   regex: '(python\w*|process_\w*)'
      #   action: drop
  - job_name: 'shakenfist_eventlog'
    static_configs:
      - targets: [
            {% for svr in groups.eventlog_node %}
              '{{hostvars[svr]['node_name']}}:13002',
            {% endfor %}
          ]
      # metric_relabel_configs:
      # - source_labels: [__name__]
      #   regex: (?i)(etcd_mvcc_db_total_size_in_bytes|etcd_network_client_grpc_received_bytes_total|etcd_network_client_grpc_sent_bytes_total|etcd_disk_wal_fsync_duration_seconds)
      #   action: keep
  - job_name: 'etcd'
    static_configs:
      - targets: [
            {% for svr in groups.etcd_master %}
              '{{hostvars[svr]['node_name']}}:2379',
            {% endfor %}
          ]
      # metric_relabel_configs:
      # - source_labels: [__name__]
      #   regex: (?i)(etcd_mvcc_db_total_size_in_bytes|etcd_network_client_grpc_received_bytes_total|etcd_network_client_grpc_sent_bytes_total|etcd_disk_wal_fsync_duration_seconds)
      #   action: keep