# generated by datamodel-codegen:
#   filename:  defaultsettings.json
#   timestamp: 2020-10-19T11:01:54+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    API_PORT: int
    API_TIMEOUT: int
    API_ASYNC_WAIT: int
    INCLUDE_TRACEBACKS: bool
    PROMETHEUS_METRICS_PORT: int
    AUTH_SECRET_SEED: str
    API_COMMAND_LINE: str
    SCHEDULER_CACHE_TIMEOUT: int
    CPU_OVERCOMMIT_RATIO: int
    RAM_OVERCOMMIT_RATIO: float
    RAM_SYSTEM_RESERVATION: float
    FLOATING_NETWORK: str
    NETWORK_NODE_IP: Any
    CLEANER_DELAY: int
    ZONE: str
    DOWNLOAD_URL_CIRROS: str
    DOWNLOAD_URL_UBUNTU: str
    DISK_BUS: str
    DISK_FORMAT: str
    NODE_IP: Any
    NODE_NAME: Any
    NODE_EGRESS_NIC: str
    STORAGE_PATH: str
    SLOW_LOCK_THRESHOLD: float
    LOGLEVEL_API: str
    LOGLEVEL_CLEANER: str
    LOGLEVEL_MAIN: str
    LOGLEVEL_NET: str
    LOGLEVEL_RESOURCES: str
    LOGLEVEL_TRIGGERS: str
    LOG_METHOD_TRACE: int
