# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nodelock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nodelock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enodelock.proto\x12\x11shakenfist.protos\"-\n\x0bLockRequest\x12\x11\n\trequester\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"/\n\rUnlockRequest\x12\x11\n\trequester\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x90\x01\n\x0fNodeLockRequest\x12\x36\n\x0clock_request\x18\x01 \x01(\x0b\x32\x1e.shakenfist.protos.LockRequestH\x00\x12:\n\x0eunlock_request\x18\x02 \x01(\x0b\x32 .shakenfist.protos.UnlockRequestH\x00\x42\t\n\x07request\"s\n\tLockReply\x12\x35\n\x07outcome\x18\x01 \x01(\x0e\x32$.shakenfist.protos.LockReply.Outcome\"/\n\x07Outcome\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0c\x41LREADY_HELD\x10\x01\x12\n\n\x06\x44\x45NIED\x10\x02\"g\n\x0bUnlockReply\x12\x37\n\x07outcome\x18\x01 \x01(\x0e\x32&.shakenfist.protos.UnlockReply.Outcome\"\x1f\n\x07Outcome\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08NOT_HELD\x10\x02\"\x84\x01\n\rNodeLockReply\x12\x32\n\nlock_reply\x18\x01 \x01(\x0b\x32\x1c.shakenfist.protos.LockReplyH\x00\x12\x36\n\x0cunlock_reply\x18\x02 \x01(\x0b\x32\x1e.shakenfist.protos.UnlockReplyH\x00\x42\x07\n\x05replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nodelock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCKREQUEST']._serialized_start=37
  _globals['_LOCKREQUEST']._serialized_end=82
  _globals['_UNLOCKREQUEST']._serialized_start=84
  _globals['_UNLOCKREQUEST']._serialized_end=131
  _globals['_NODELOCKREQUEST']._serialized_start=134
  _globals['_NODELOCKREQUEST']._serialized_end=278
  _globals['_LOCKREPLY']._serialized_start=280
  _globals['_LOCKREPLY']._serialized_end=395
  _globals['_LOCKREPLY_OUTCOME']._serialized_start=348
  _globals['_LOCKREPLY_OUTCOME']._serialized_end=395
  _globals['_UNLOCKREPLY']._serialized_start=397
  _globals['_UNLOCKREPLY']._serialized_end=500
  _globals['_UNLOCKREPLY_OUTCOME']._serialized_start=469
  _globals['_UNLOCKREPLY_OUTCOME']._serialized_end=500
  _globals['_NODELOCKREPLY']._serialized_start=503
  _globals['_NODELOCKREPLY']._serialized_end=635
# @@protoc_insertion_point(module_scope)
