# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: privexec.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'privexec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprivexec.proto\x12\x11shakenfist.protos\"2\n\x13\x45nvironmentVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xb8\x02\n\x0e\x45xecuteRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x45\n\x15\x65nvironment_variables\x18\x02 \x03(\x0b\x32&.shakenfist.protos.EnvironmentVariable\x12\x19\n\x11network_namespace\x18\x03 \x01(\t\x12\x41\n\x0bio_priority\x18\x04 \x01(\x0e\x32,.shakenfist.protos.ExecuteRequest.IOPriority\x12\x19\n\x11working_directory\x18\x05 \x01(\t\x12\x12\n\nrequest_id\x18\x06 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x07 \x01(\t\"+\n\nIOPriority\x12\n\n\x06NORMAL\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02\"R\n\x07Request\x12<\n\x0f\x65xecute_request\x18\x01 \x01(\x0b\x32!.shakenfist.protos.ExecuteRequestH\x00\x42\t\n\x07request\"\x86\x01\n\x0c\x45xecuteReply\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x05 \x01(\t\x12\x19\n\x11\x65xecution_seconds\x18\x06 \x01(\x01\"J\n\x05Reply\x12\x38\n\rexecute_reply\x18\x01 \x01(\x0b\x32\x1f.shakenfist.protos.ExecuteReplyH\x00\x42\x07\n\x05replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'privexec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIRONMENTVARIABLE']._serialized_start=37
  _globals['_ENVIRONMENTVARIABLE']._serialized_end=87
  _globals['_EXECUTEREQUEST']._serialized_start=90
  _globals['_EXECUTEREQUEST']._serialized_end=402
  _globals['_EXECUTEREQUEST_IOPRIORITY']._serialized_start=359
  _globals['_EXECUTEREQUEST_IOPRIORITY']._serialized_end=402
  _globals['_REQUEST']._serialized_start=404
  _globals['_REQUEST']._serialized_end=486
  _globals['_EXECUTEREPLY']._serialized_start=489
  _globals['_EXECUTEREPLY']._serialized_end=623
  _globals['_REPLY']._serialized_start=625
  _globals['_REPLY']._serialized_end=699
# @@protoc_insertion_point(module_scope)
