---
- debug:
    msg: "Executing network role action {{ role_action }}."
  delegate_to: localhost
  run_once: true

- include_tasks: "{{ role_action }}.yml"

- debug:
    msg: "Completed network role action {{ role_action }}."
  delegate_to: localhost
  run_once: true