---
- name: Determine the mesh network interface MTU
  shell: ip link show
  register: ip_links

- name: Log network interfaces
  debug:
    msg: "{{ip_links.stdout}}"

- name: Determine the mesh network interface MTU
  shell: ip link show {{node_mesh_nic}} | grep mtu | sed -e 's/.*mtu //' -e 's/ .*//'
  register: node_mtu_complex

- name: Extract default interface MTU
  set_fact:
    node_mtu: "{{node_mtu_complex.stdout}}"

- name: Log node MTU
  debug:
    msg: "Node MTU is {{node_mtu}}"

- name: Abort if default interface MTU is too low
  fail:
    msg: "Node MTU is too low."
  when: ignore_mtu != "1" and node_mtu|int < 2000