{
 "title": "Shaken Fist Busy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load Average (5 mins)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_load_5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instance vCPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_total_instance_vcpus", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instance CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_total_instance_cpu_time[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instances total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instances_total", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "SF Alerts", "type": "alertlist", "gridPos": { "h": 15, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Memory Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "memory_max * 1024 * 1024", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(memory_available * 1024 * 1024)",
     "legendFormat": "Memory available"
    },
    {
     "expr": "sum(memory_ksm_pages_sharing * 4096)\n",
     "legendFormat": "Memory shared"
    }
   ]
  },
  {
   "title": "Instance memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "memory_total_instance_actual * 1024 * 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_queue_processing", "legendFormat": "Processing" },
    { "expr": "network_queue_waiting", "legendFormat": "Waiting" }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(disk_free, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(node_queue_waiting, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "etcd Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} In"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Out"
    }
   ]
  },
  {
   "title": "etcd DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(etcd_mvcc_db_total_size_in_bytes, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}