# shared
system_key: "unknown"
etcd_host: "127.0.0.1"
node_name: "localhost"
node_mesh_ip: "127.0.0.1"

# bootstrap
server_package: "shakenfist"
client_package: "shakenfist-client"
pip_extra: ""

# syslog
syslog_target: "unknown"

# config
sf_config_template_path: "unknown"

# register
# ...