---
- name: Install apache2
  apt:
    name: apache2
    state: latest
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Enable proxy modules for apache
  shell: a2enmod proxy proxy_http lbmethod_byrequests

- name: Write apache site
  template:
    src: files/apache-site-primary.conf
    dest: /etc/apache2/sites-available/sf-example.conf
    owner: root
    group: root
    mode: ugo+r

- name: Restart apache
  service:
    name: apache2
    enabled: yes
    state: restarted