---
- name: Set auth secret in cluster config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        AUTH_SECRET_SEED "{{ auth_secret }}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"

- name: Set ram reservation in cluster config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        RAM_SYSTEM_RESERVATION "{{ ram_system_reservation }}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"

- name: Set lowest_mtu in cluster config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        MAX_HYPERVISOR_MTU "{{ lowest_mtu }}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"

- name: Set DNS server in cluster config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        DNS_SERVER "{{ dns_server }}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"

- name: Set HTTP proxy in cluster config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        HTTP_PROXY "{{ http_proxy }}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"
  when: hostvars['localhost']['http_proxy'] | length != 0

- name: Log additional config
  debug:
    msg: "{{ extra_config | from_json }}"

- name: Apply additional config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-config \
        "{{item['name']}}" "{{item['value']}}"
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"
  loop: "{{ extra_config | from_json }}"

- name: Verify configuration
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl verify-config
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"

- name: Parse back cluster configuration
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl show-config
  environment:
    SHAKENFIST_DATABASE_NODE_IP: "{{ database_node_ip }}"
  register: cluster_config

- name: Log cluster config
  debug:
    msg: "{{ cluster_config.stdout }}"
