---
- name: Set auth secret in etcd
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        AUTH_SECRET_SEED "{{ auth_secret }}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"

- name: Set ram reservation in etcd
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        RAM_SYSTEM_RESERVATION "{{ ram_system_reservation }}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"

- name: Set lowest_mtu in etcd
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        MAX_HYPERVISOR_MTU "{{ lowest_mtu }}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"

- name: Set DNS server in etcd
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        DNS_SERVER "{{ dns_server }}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"

- name: Set HTTP proxy in etcd
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        HTTP_PROXY "{{ http_proxy }}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"
  when: hostvars['localhost']['http_proxy'] | length != 0

- name: Log additional config
  debug:
    msg: "{{ extra_config | from_json }}"

- name: Apply additional config
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl set-etcd-config \
        "{{item['name']}}" "{{item['value']}}"
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"
  loop: "{{ extra_config | from_json }}"

- name: Verify configuration
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl verify-config
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"

- name: Parse back etcd configuration
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl show-etcd-config
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"
  register: etcd_config

- name: Log etcd config
  debug:
    msg: "{{ etcd_config.stdout }}"