---
- name: Install prometheus
  apt:
    name: prometheus
    state: latest

- name: Write prometheus configuration file
  template:
    src: templates/etc_prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    mode: u=rw,g=r,o=r

- name: Restart prometheus
  service:
    name: prometheus
    enabled: yes
    state: restarted

- name: Install Grafana prerequisites
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    update_cache: yes
    state: latest

- name: Check if grafana packages are already setup
  stat:
    path: /etc/apt/sources.list.d/packages_grafana_com_oss_deb.list
  register: stat_result

- name: Add Grafana GPG key
  apt_key: url=https://packages.grafana.com/gpg.key
  when: not stat_result.stat.exists

- name: Add Grafana APT repository
  apt_repository:
    repo: deb [arch=amd64] http://packages.grafana.com/oss/deb stable main
  when: not stat_result.stat.exists

- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes
    state: latest

- name: Write grafana config
  template:
    src: templates/grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    mode: u=rw,g=r,o=r

- name: Write grafana dashboard
  copy:
    src: files/grafana/provisioning/dashboards/shakenfist.json
    dest: /etc/grafana/provisioning/dashboards/shakenfist.json
    owner: root
    mode: u=rw,g=r,o=r

- name: Write grafana dashboard config
  copy:
    src: files/grafana/provisioning/dashboards/dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
    owner: root
    mode: u=rw,g=r,o=r

- name: Write prometheus grafana configuration file
  template:
    src: templates/ds_prometheus.yml
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    mode: u=rwx,g=r,o=r

- name: Restart grafana
  service:
    name: grafana-server
    enabled: yes
    state: restarted
