---
- name: Install prometheus
  apt:
    name: prometheus
    state: latest
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Write prometheus configuration file
  template:
    src: templates/etc_prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    mode: u=rw,g=r,o=r

- name: Restart prometheus
  service:
    name: prometheus
    enabled: yes
    state: restarted
