---
- name: Create an admin namespace called "system" with one key configured
  shell: |
    /srv/shakenfist/venv/bin/sf-ctl \
        bootstrap-system-key deploy {{ system_key }}
  environment:
    SHAKENFIST_ETCD_HOST: "{{ etcd_host }}"
    SHAKENFIST_NODE_MESH_IP: "{{ node_mesh_ip }}"
    SHAKENFIST_EVENTLOG_NODE_IP: "{{ eventlog_node_ip }}"
    SHAKENFIST_DATABASE_USE_DIRECT_ETCD: "True"
  run_once: true