role_action: "undefined"

ca_path: "/srv/shakenfist/pki/CA"
deploy_name: "sf"
hostname: "undefined"

ca_cert_path: "{{ ca_path }}/{{ deploy_name }}-ca-cert.pem"
ca_key_path: "{{ ca_path }}/{{ deploy_name }}-ca-key.pem"
ca_template_path: "{{ ca_path }}/{{ deploy_name }}-ca-template.info"

host_cert_path: "{{ ca_path }}/{{ hostname }}-server-cert.pem"
host_key_path: "{{ ca_path }}/{{ hostname }}-server-key.pem"
host_template_path: "{{ ca_path }}/{{ hostname }}-server-template.pem"