"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EnvironmentVariable(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnvironmentVariable: _TypeAlias = EnvironmentVariable  # noqa: Y015

@_typing.final
class ExecuteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _IOPriority:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _IOPriorityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ExecuteRequest._IOPriority.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NORMAL: ExecuteRequest._IOPriority.ValueType  # 0
        LOW: ExecuteRequest._IOPriority.ValueType  # 1
        HIGH: ExecuteRequest._IOPriority.ValueType  # 2

    class IOPriority(_IOPriority, metaclass=_IOPriorityEnumTypeWrapper): ...
    NORMAL: ExecuteRequest.IOPriority.ValueType  # 0
    LOW: ExecuteRequest.IOPriority.ValueType  # 1
    HIGH: ExecuteRequest.IOPriority.ValueType  # 2

    COMMAND_FIELD_NUMBER: _builtins.int
    ENVIRONMENT_VARIABLES_FIELD_NUMBER: _builtins.int
    NETWORK_NAMESPACE_FIELD_NUMBER: _builtins.int
    IO_PRIORITY_FIELD_NUMBER: _builtins.int
    WORKING_DIRECTORY_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    EXECUTION_ID_FIELD_NUMBER: _builtins.int
    command: _builtins.str
    network_namespace: _builtins.str
    io_priority: Global___ExecuteRequest.IOPriority.ValueType
    working_directory: _builtins.str
    request_id: _builtins.str
    execution_id: _builtins.str
    @_builtins.property
    def environment_variables(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnvironmentVariable]: ...
    def __init__(
        self,
        *,
        command: _builtins.str = ...,
        environment_variables: _abc.Iterable[Global___EnvironmentVariable] | None = ...,
        network_namespace: _builtins.str = ...,
        io_priority: Global___ExecuteRequest.IOPriority.ValueType = ...,
        working_directory: _builtins.str = ...,
        request_id: _builtins.str = ...,
        execution_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "environment_variables", b"environment_variables", "execution_id", b"execution_id", "io_priority", b"io_priority", "network_namespace", b"network_namespace", "request_id", b"request_id", "working_directory", b"working_directory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecuteRequest: _TypeAlias = ExecuteRequest  # noqa: Y015

@_typing.final
class ExecuteReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STDOUT_FIELD_NUMBER: _builtins.int
    STDERR_FIELD_NUMBER: _builtins.int
    EXIT_CODE_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    EXECUTION_ID_FIELD_NUMBER: _builtins.int
    EXECUTION_SECONDS_FIELD_NUMBER: _builtins.int
    stdout: _builtins.str
    stderr: _builtins.str
    exit_code: _builtins.int
    request_id: _builtins.str
    execution_id: _builtins.str
    execution_seconds: _builtins.float
    def __init__(
        self,
        *,
        stdout: _builtins.str = ...,
        stderr: _builtins.str = ...,
        exit_code: _builtins.int = ...,
        request_id: _builtins.str = ...,
        execution_id: _builtins.str = ...,
        execution_seconds: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["execution_id", b"execution_id", "execution_seconds", b"execution_seconds", "exit_code", b"exit_code", "request_id", b"request_id", "stderr", b"stderr", "stdout", b"stdout"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecuteReply: _TypeAlias = ExecuteReply  # noqa: Y015
