"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from shakenfist.protos import shakenfist_enums_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StatusReply(google.protobuf.message.Message):
    """Generic status reply"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "success", b"success"]) -> None: ...

global___StatusReply = StatusReply

@typing.final
class GetRequest(google.protobuf.message.Message):
    """Key-Value Operations"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___GetRequest = GetRequest

@typing.final
class GetReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    value: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["found", b"found", "value", b"value"]) -> None: ...

global___GetReply = GetReply

@typing.final
class GetPrefixRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    prefix: builtins.str
    limit: builtins.int
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        prefix: builtins.str = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "object_type", b"object_type", "prefix", b"prefix", "subtype", b"subtype"]) -> None: ...

global___GetPrefixRequest = GetPrefixRequest

@typing.final
class KeyValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

global___KeyValue = KeyValue

@typing.final
class GetPrefixReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___KeyValue]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___KeyValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

global___GetPrefixReply = GetPrefixReply

@typing.final
class PutRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    data: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
        data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___PutRequest = PutRequest

@typing.final
class CreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    data: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
        data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___CreateRequest = CreateRequest

@typing.final
class DeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___DeleteRequest = DeleteRequest

@typing.final
class DeletePrefixRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["path", b"path"]) -> None: ...

global___DeletePrefixRequest = DeletePrefixRequest

@typing.final
class Mutation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    ORIGINAL_DATA_FIELD_NUMBER: builtins.int
    NEW_DATA_FIELD_NUMBER: builtins.int
    ORIGINAL_IS_NONE_FIELD_NUMBER: builtins.int
    NEW_IS_NONE_FIELD_NUMBER: builtins.int
    path: builtins.str
    original_data: builtins.str
    """JSON-encoded, empty string for None"""
    new_data: builtins.str
    """JSON-encoded, empty string for None (delete)"""
    original_is_none: builtins.bool
    new_is_none: builtins.bool
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        original_data: builtins.str = ...,
        new_data: builtins.str = ...,
        original_is_none: builtins.bool = ...,
        new_is_none: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_data", b"new_data", "new_is_none", b"new_is_none", "original_data", b"original_data", "original_is_none", b"original_is_none", "path", b"path"]) -> None: ...

global___Mutation = Mutation

@typing.final
class ReplaceManyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MUTATIONS_FIELD_NUMBER: builtins.int
    SUPPRESS_FAILURE_AUDIT_FIELD_NUMBER: builtins.int
    suppress_failure_audit: builtins.bool
    @property
    def mutations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Mutation]: ...
    def __init__(
        self,
        *,
        mutations: collections.abc.Iterable[global___Mutation] | None = ...,
        suppress_failure_audit: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mutations", b"mutations", "suppress_failure_audit", b"suppress_failure_audit"]) -> None: ...

global___ReplaceManyRequest = ReplaceManyRequest

@typing.final
class MutationFailure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    DESIRED_FIELD_NUMBER: builtins.int
    ACTUAL_FIELD_NUMBER: builtins.int
    REPLACEMENT_FIELD_NUMBER: builtins.int
    path: builtins.str
    desired: builtins.str
    actual: builtins.str
    replacement: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        desired: builtins.str = ...,
        actual: builtins.str = ...,
        replacement: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actual", b"actual", "desired", b"desired", "path", b"path", "replacement", b"replacement"]) -> None: ...

global___MutationFailure = MutationFailure

@typing.final
class ReplaceManyReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    FAILURES_FIELD_NUMBER: builtins.int
    success: builtins.bool
    @property
    def failures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MutationFailure]: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        failures: collections.abc.Iterable[global___MutationFailure] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["failures", b"failures", "success", b"success"]) -> None: ...

global___ReplaceManyReply = ReplaceManyReply

@typing.final
class EnqueueRequest(google.protobuf.message.Message):
    """Queue Operations"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    WORK_ITEM_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    work_item: builtins.str
    """JSON-encoded data"""
    delay: builtins.float
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        work_item: builtins.str = ...,
        delay: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "queue_name", b"queue_name", "work_item", b"work_item"]) -> None: ...

global___EnqueueRequest = EnqueueRequest

@typing.final
class DequeueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["queue_name", b"queue_name"]) -> None: ...

global___DequeueRequest = DequeueRequest

@typing.final
class DequeueReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    JOB_NAME_FIELD_NUMBER: builtins.int
    WORK_ITEM_FIELD_NUMBER: builtins.int
    found: builtins.bool
    job_name: builtins.str
    work_item: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        job_name: builtins.str = ...,
        work_item: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["found", b"found", "job_name", b"job_name", "work_item", b"work_item"]) -> None: ...

global___DequeueReply = DequeueReply

@typing.final
class ResolveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    JOB_NAME_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    job_name: builtins.str
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        job_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["job_name", b"job_name", "queue_name", b"queue_name"]) -> None: ...

global___ResolveRequest = ResolveRequest

@typing.final
class QueueLengthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["queue_name", b"queue_name"]) -> None: ...

global___QueueLengthRequest = QueueLengthRequest

@typing.final
class QueueLengthReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESSING_FIELD_NUMBER: builtins.int
    QUEUED_FIELD_NUMBER: builtins.int
    DEFERRED_FIELD_NUMBER: builtins.int
    processing: builtins.int
    queued: builtins.int
    deferred: builtins.int
    def __init__(
        self,
        *,
        processing: builtins.int = ...,
        queued: builtins.int = ...,
        deferred: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deferred", b"deferred", "processing", b"processing", "queued", b"queued"]) -> None: ...

global___QueueLengthReply = QueueLengthReply

@typing.final
class RestartQueueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["queue_name", b"queue_name"]) -> None: ...

global___RestartQueueRequest = RestartQueueRequest

@typing.final
class ClusterLockRequest(google.protobuf.message.Message):
    """Lock Operations"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    LOCK_DATA_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    lock_data: builtins.str
    """JSON-encoded lock holder info"""
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
        lock_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lock_data", b"lock_data", "name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___ClusterLockRequest = ClusterLockRequest

@typing.final
class ClusterLockReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACQUIRED_FIELD_NUMBER: builtins.int
    acquired: builtins.bool
    def __init__(
        self,
        *,
        acquired: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["acquired", b"acquired"]) -> None: ...

global___ClusterLockReply = ClusterLockReply

@typing.final
class ClusterReleaseLockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    LOCK_DATA_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    lock_data: builtins.str
    """JSON-encoded, for CAS verification"""
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
        lock_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lock_data", b"lock_data", "name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___ClusterReleaseLockRequest = ClusterReleaseLockRequest

@typing.final
class ClusterGetLockHolderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    subtype: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        subtype: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "object_type", b"object_type", "subtype", b"subtype"]) -> None: ...

global___ClusterGetLockHolderRequest = ClusterGetLockHolderRequest

@typing.final
class ClusterLockHolderReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HELD_FIELD_NUMBER: builtins.int
    HOLDER_FIELD_NUMBER: builtins.int
    held: builtins.bool
    holder: builtins.str
    """JSON-encoded lock holder info"""
    def __init__(
        self,
        *,
        held: builtins.bool = ...,
        holder: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["held", b"held", "holder", b"holder"]) -> None: ...

global___ClusterLockHolderReply = ClusterLockHolderReply

@typing.final
class ClusterClearStaleLocksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_NAME_FIELD_NUMBER: builtins.int
    node_name: builtins.str
    def __init__(
        self,
        *,
        node_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_name", b"node_name"]) -> None: ...

global___ClusterClearStaleLocksRequest = ClusterClearStaleLocksRequest

@typing.final
class ClusterGetExistingLocksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ClusterGetExistingLocksRequest = ClusterGetExistingLocksRequest

@typing.final
class ClusterLockEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    HOLDER_FIELD_NUMBER: builtins.int
    key: builtins.str
    holder: builtins.str
    """JSON-encoded lock holder info"""
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        holder: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["holder", b"holder", "key", b"key"]) -> None: ...

global___ClusterLockEntry = ClusterLockEntry

@typing.final
class ClusterGetExistingLocksReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCKS_FIELD_NUMBER: builtins.int
    @property
    def locks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClusterLockEntry]: ...
    def __init__(
        self,
        *,
        locks: collections.abc.Iterable[global___ClusterLockEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["locks", b"locks"]) -> None: ...

global___ClusterGetExistingLocksReply = ClusterGetExistingLocksReply

@typing.final
class CompactRequest(google.protobuf.message.Message):
    """Maintenance Operations"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REVISION_FIELD_NUMBER: builtins.int
    revision: builtins.int
    def __init__(
        self,
        *,
        revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["revision", b"revision"]) -> None: ...

global___CompactRequest = CompactRequest

@typing.final
class GetObjectStateRequest(google.protobuf.message.Message):
    """Object State Operations (MariaDB)
    These operations manage object state in MariaDB, which is used for
    efficient state queries and persistence.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_UUID_FIELD_NUMBER: builtins.int
    object_type: shakenfist_enums_pb2.ObjectType.ValueType
    """The type of object"""
    object_uuid: builtins.str
    def __init__(
        self,
        *,
        object_type: shakenfist_enums_pb2.ObjectType.ValueType = ...,
        object_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_type", b"object_type", "object_uuid", b"object_uuid"]) -> None: ...

global___GetObjectStateRequest = GetObjectStateRequest

@typing.final
class GetObjectStateReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    STATE_VALUE_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    state_value: builtins.str
    """The state string, e.g., 'created', 'deleted'"""
    update_time: builtins.float
    """Unix timestamp of last update"""
    message: builtins.str
    """Optional message explaining the state"""
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        state_value: builtins.str = ...,
        update_time: builtins.float = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["found", b"found", "message", b"message", "state_value", b"state_value", "update_time", b"update_time"]) -> None: ...

global___GetObjectStateReply = GetObjectStateReply

@typing.final
class SetObjectStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_UUID_FIELD_NUMBER: builtins.int
    STATE_VALUE_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    object_type: shakenfist_enums_pb2.ObjectType.ValueType
    object_uuid: builtins.str
    state_value: builtins.str
    update_time: builtins.float
    message: builtins.str
    """Optional"""
    def __init__(
        self,
        *,
        object_type: shakenfist_enums_pb2.ObjectType.ValueType = ...,
        object_uuid: builtins.str = ...,
        state_value: builtins.str = ...,
        update_time: builtins.float = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "object_type", b"object_type", "object_uuid", b"object_uuid", "state_value", b"state_value", "update_time", b"update_time"]) -> None: ...

global___SetObjectStateRequest = SetObjectStateRequest

@typing.final
class DeleteObjectStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_UUID_FIELD_NUMBER: builtins.int
    object_type: shakenfist_enums_pb2.ObjectType.ValueType
    object_uuid: builtins.str
    def __init__(
        self,
        *,
        object_type: shakenfist_enums_pb2.ObjectType.ValueType = ...,
        object_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_type", b"object_type", "object_uuid", b"object_uuid"]) -> None: ...

global___DeleteObjectStateRequest = DeleteObjectStateRequest

@typing.final
class GetObjectsByStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    STATE_VALUES_FIELD_NUMBER: builtins.int
    object_type: shakenfist_enums_pb2.ObjectType.ValueType
    @property
    def state_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of states to match"""

    def __init__(
        self,
        *,
        object_type: shakenfist_enums_pb2.ObjectType.ValueType = ...,
        state_values: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_type", b"object_type", "state_values", b"state_values"]) -> None: ...

global___GetObjectsByStateRequest = GetObjectsByStateRequest

@typing.final
class GetObjectsByStateReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_UUIDS_FIELD_NUMBER: builtins.int
    @property
    def object_uuids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        object_uuids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_uuids", b"object_uuids"]) -> None: ...

global___GetObjectsByStateReply = GetObjectsByStateReply

@typing.final
class IPAMReservationData(google.protobuf.message.Message):
    """IPAM Reservation Operations (MariaDB)
    These operations manage IP address reservations in MariaDB for atomic
    address allocation and efficient queries.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    RESERVATION_TYPE_FIELD_NUMBER: builtins.int
    USER_TYPE_FIELD_NUMBER: builtins.int
    USER_UUID_FIELD_NUMBER: builtins.int
    RESERVED_AT_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    address: builtins.str
    reservation_type: shakenfist_enums_pb2.ReservationType.ValueType
    """How this address is being used"""
    user_type: shakenfist_enums_pb2.ObjectType.ValueType
    """Object type using this address"""
    user_uuid: builtins.str
    """UUID of object using this address"""
    reserved_at: builtins.float
    """Unix timestamp when reserved"""
    comment: builtins.str
    """Optional description"""
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
        address: builtins.str = ...,
        reservation_type: shakenfist_enums_pb2.ReservationType.ValueType = ...,
        user_type: shakenfist_enums_pb2.ObjectType.ValueType = ...,
        user_uuid: builtins.str = ...,
        reserved_at: builtins.float = ...,
        comment: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "comment", b"comment", "ipam_uuid", b"ipam_uuid", "reservation_type", b"reservation_type", "reserved_at", b"reserved_at", "user_type", b"user_type", "user_uuid", b"user_uuid"]) -> None: ...

global___IPAMReservationData = IPAMReservationData

@typing.final
class ReserveAddressRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESERVATION_FIELD_NUMBER: builtins.int
    @property
    def reservation(self) -> global___IPAMReservationData: ...
    def __init__(
        self,
        *,
        reservation: global___IPAMReservationData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["reservation", b"reservation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["reservation", b"reservation"]) -> None: ...

global___ReserveAddressRequest = ReserveAddressRequest

@typing.final
class ReleaseAddressRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    HALO_RESERVATION_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    address: builtins.str
    @property
    def halo_reservation(self) -> global___IPAMReservationData:
        """The deletion-halo data to set"""

    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
        address: builtins.str = ...,
        halo_reservation: global___IPAMReservationData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["halo_reservation", b"halo_reservation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "halo_reservation", b"halo_reservation", "ipam_uuid", b"ipam_uuid"]) -> None: ...

global___ReleaseAddressRequest = ReleaseAddressRequest

@typing.final
class GetReservationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "ipam_uuid", b"ipam_uuid"]) -> None: ...

global___GetReservationRequest = GetReservationRequest

@typing.final
class GetReservationReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    RESERVATION_FIELD_NUMBER: builtins.int
    found: builtins.bool
    @property
    def reservation(self) -> global___IPAMReservationData: ...
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        reservation: global___IPAMReservationData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["reservation", b"reservation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["found", b"found", "reservation", b"reservation"]) -> None: ...

global___GetReservationReply = GetReservationReply

@typing.final
class GetReservationsForIPAMRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ipam_uuid", b"ipam_uuid"]) -> None: ...

global___GetReservationsForIPAMRequest = GetReservationsForIPAMRequest

@typing.final
class GetReservationsForIPAMReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESERVATIONS_FIELD_NUMBER: builtins.int
    @property
    def reservations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPAMReservationData]: ...
    def __init__(
        self,
        *,
        reservations: collections.abc.Iterable[global___IPAMReservationData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["reservations", b"reservations"]) -> None: ...

global___GetReservationsForIPAMReply = GetReservationsForIPAMReply

@typing.final
class DeleteReservationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "ipam_uuid", b"ipam_uuid"]) -> None: ...

global___DeleteReservationRequest = DeleteReservationRequest

@typing.final
class DeleteReservationsForIPAMRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ipam_uuid", b"ipam_uuid"]) -> None: ...

global___DeleteReservationsForIPAMRequest = DeleteReservationsForIPAMRequest

@typing.final
class DeleteCountReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNT_FIELD_NUMBER: builtins.int
    count: builtins.int
    def __init__(
        self,
        *,
        count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["count", b"count"]) -> None: ...

global___DeleteCountReply = DeleteCountReply

@typing.final
class ReleaseHaloedAddressesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    OLDER_THAN_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    older_than: builtins.float
    """Unix timestamp - delete halos reserved before this"""
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
        older_than: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ipam_uuid", b"ipam_uuid", "older_than", b"older_than"]) -> None: ...

global___ReleaseHaloedAddressesRequest = ReleaseHaloedAddressesRequest

@typing.final
class GetAddressesInUseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IPAM_UUID_FIELD_NUMBER: builtins.int
    ipam_uuid: builtins.str
    def __init__(
        self,
        *,
        ipam_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ipam_uuid", b"ipam_uuid"]) -> None: ...

global___GetAddressesInUseRequest = GetAddressesInUseRequest

@typing.final
class GetAddressesInUseReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESSES_FIELD_NUMBER: builtins.int
    @property
    def addresses(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        addresses: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addresses", b"addresses"]) -> None: ...

global___GetAddressesInUseReply = GetAddressesInUseReply
