# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shakenfist.protos import database_pb2 as database__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in database_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Get',
                request_serializer=database__pb2.GetRequest.SerializeToString,
                response_deserializer=database__pb2.GetReply.FromString,
                _registered_method=True)
        self.GetPrefix = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetPrefix',
                request_serializer=database__pb2.GetPrefixRequest.SerializeToString,
                response_deserializer=database__pb2.GetPrefixReply.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Put',
                request_serializer=database__pb2.PutRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Create',
                request_serializer=database__pb2.CreateRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Delete',
                request_serializer=database__pb2.DeleteRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeletePrefix = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeletePrefix',
                request_serializer=database__pb2.DeletePrefixRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ReplaceMany = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ReplaceMany',
                request_serializer=database__pb2.ReplaceManyRequest.SerializeToString,
                response_deserializer=database__pb2.ReplaceManyReply.FromString,
                _registered_method=True)
        self.Enqueue = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Enqueue',
                request_serializer=database__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Dequeue = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Dequeue',
                request_serializer=database__pb2.DequeueRequest.SerializeToString,
                response_deserializer=database__pb2.DequeueReply.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Resolve',
                request_serializer=database__pb2.ResolveRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetQueueLength = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetQueueLength',
                request_serializer=database__pb2.QueueLengthRequest.SerializeToString,
                response_deserializer=database__pb2.QueueLengthReply.FromString,
                _registered_method=True)
        self.RestartQueue = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/RestartQueue',
                request_serializer=database__pb2.RestartQueueRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.AcquireLock = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/AcquireLock',
                request_serializer=database__pb2.ClusterLockRequest.SerializeToString,
                response_deserializer=database__pb2.ClusterLockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ReleaseLock',
                request_serializer=database__pb2.ClusterReleaseLockRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetLockHolder = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetLockHolder',
                request_serializer=database__pb2.ClusterGetLockHolderRequest.SerializeToString,
                response_deserializer=database__pb2.ClusterLockHolderReply.FromString,
                _registered_method=True)
        self.ClearStaleLocks = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ClearStaleLocks',
                request_serializer=database__pb2.ClusterClearStaleLocksRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetExistingLocks = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetExistingLocks',
                request_serializer=database__pb2.ClusterGetExistingLocksRequest.SerializeToString,
                response_deserializer=database__pb2.ClusterGetExistingLocksReply.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/Compact',
                request_serializer=database__pb2.CompactRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetObjectState = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetObjectState',
                request_serializer=database__pb2.GetObjectStateRequest.SerializeToString,
                response_deserializer=database__pb2.GetObjectStateReply.FromString,
                _registered_method=True)
        self.SetObjectState = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/SetObjectState',
                request_serializer=database__pb2.SetObjectStateRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeleteObjectState = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeleteObjectState',
                request_serializer=database__pb2.DeleteObjectStateRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetObjectsByState = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetObjectsByState',
                request_serializer=database__pb2.GetObjectsByStateRequest.SerializeToString,
                response_deserializer=database__pb2.GetObjectsByStateReply.FromString,
                _registered_method=True)
        self.ReserveAddress = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ReserveAddress',
                request_serializer=database__pb2.ReserveAddressRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ReleaseAddress = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ReleaseAddress',
                request_serializer=database__pb2.ReleaseAddressRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetReservation = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetReservation',
                request_serializer=database__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=database__pb2.GetReservationReply.FromString,
                _registered_method=True)
        self.GetReservationsForIPAM = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetReservationsForIPAM',
                request_serializer=database__pb2.GetReservationsForIPAMRequest.SerializeToString,
                response_deserializer=database__pb2.GetReservationsForIPAMReply.FromString,
                _registered_method=True)
        self.DeleteReservation = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeleteReservation',
                request_serializer=database__pb2.DeleteReservationRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeleteReservationsForIPAM = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeleteReservationsForIPAM',
                request_serializer=database__pb2.DeleteReservationsForIPAMRequest.SerializeToString,
                response_deserializer=database__pb2.DeleteCountReply.FromString,
                _registered_method=True)
        self.ReleaseHaloedAddresses = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/ReleaseHaloedAddresses',
                request_serializer=database__pb2.ReleaseHaloedAddressesRequest.SerializeToString,
                response_deserializer=database__pb2.DeleteCountReply.FromString,
                _registered_method=True)
        self.GetAddressesInUse = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetAddressesInUse',
                request_serializer=database__pb2.GetAddressesInUseRequest.SerializeToString,
                response_deserializer=database__pb2.GetAddressesInUseReply.FromString,
                _registered_method=True)
        self.CreateUpload = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/CreateUpload',
                request_serializer=database__pb2.CreateUploadRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetUpload = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetUpload',
                request_serializer=database__pb2.GetUploadRequest.SerializeToString,
                response_deserializer=database__pb2.GetUploadReply.FromString,
                _registered_method=True)
        self.GetUploads = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetUploads',
                request_serializer=database__pb2.GetUploadsRequest.SerializeToString,
                response_deserializer=database__pb2.GetUploadsReply.FromString,
                _registered_method=True)
        self.DeleteUpload = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeleteUpload',
                request_serializer=database__pb2.DeleteUploadRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.UpdateUpload = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/UpdateUpload',
                request_serializer=database__pb2.UpdateUploadRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.CreateDnsMasq = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/CreateDnsMasq',
                request_serializer=database__pb2.CreateDnsMasqRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetDnsMasq = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetDnsMasq',
                request_serializer=database__pb2.GetDnsMasqRequest.SerializeToString,
                response_deserializer=database__pb2.GetDnsMasqReply.FromString,
                _registered_method=True)
        self.GetDnsMasqs = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/GetDnsMasqs',
                request_serializer=database__pb2.GetDnsMasqsRequest.SerializeToString,
                response_deserializer=database__pb2.GetDnsMasqsReply.FromString,
                _registered_method=True)
        self.DeleteDnsMasq = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/DeleteDnsMasq',
                request_serializer=database__pb2.DeleteDnsMasqRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)
        self.UpdateDnsMasq = channel.unary_unary(
                '/shakenfist.protos.DatabaseService/UpdateDnsMasq',
                request_serializer=database__pb2.UpdateDnsMasqRequest.SerializeToString,
                response_deserializer=database__pb2.StatusReply.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Key-Value Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enqueue(self, request, context):
        """Queue Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireLock(self, request, context):
        """Lock Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLockHolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearStaleLocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExistingLocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Maintenance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectState(self, request, context):
        """Object State Operations (MariaDB)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObjectState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectsByState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveAddress(self, request, context):
        """IPAM Reservation Operations (MariaDB)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservationsForIPAM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReservationsForIPAM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseHaloedAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddressesInUse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUpload(self, request, context):
        """Upload Operations (MariaDB)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDnsMasq(self, request, context):
        """DnsMasq Operations (MariaDB)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDnsMasq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDnsMasqs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDnsMasq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDnsMasq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=database__pb2.GetRequest.FromString,
                    response_serializer=database__pb2.GetReply.SerializeToString,
            ),
            'GetPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrefix,
                    request_deserializer=database__pb2.GetPrefixRequest.FromString,
                    response_serializer=database__pb2.GetPrefixReply.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=database__pb2.PutRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=database__pb2.CreateRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=database__pb2.DeleteRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'DeletePrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePrefix,
                    request_deserializer=database__pb2.DeletePrefixRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'ReplaceMany': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceMany,
                    request_deserializer=database__pb2.ReplaceManyRequest.FromString,
                    response_serializer=database__pb2.ReplaceManyReply.SerializeToString,
            ),
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=database__pb2.EnqueueRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=database__pb2.DequeueRequest.FromString,
                    response_serializer=database__pb2.DequeueReply.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=database__pb2.ResolveRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetQueueLength': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueLength,
                    request_deserializer=database__pb2.QueueLengthRequest.FromString,
                    response_serializer=database__pb2.QueueLengthReply.SerializeToString,
            ),
            'RestartQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartQueue,
                    request_deserializer=database__pb2.RestartQueueRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=database__pb2.ClusterLockRequest.FromString,
                    response_serializer=database__pb2.ClusterLockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=database__pb2.ClusterReleaseLockRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetLockHolder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLockHolder,
                    request_deserializer=database__pb2.ClusterGetLockHolderRequest.FromString,
                    response_serializer=database__pb2.ClusterLockHolderReply.SerializeToString,
            ),
            'ClearStaleLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearStaleLocks,
                    request_deserializer=database__pb2.ClusterClearStaleLocksRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetExistingLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExistingLocks,
                    request_deserializer=database__pb2.ClusterGetExistingLocksRequest.FromString,
                    response_serializer=database__pb2.ClusterGetExistingLocksReply.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=database__pb2.CompactRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetObjectState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectState,
                    request_deserializer=database__pb2.GetObjectStateRequest.FromString,
                    response_serializer=database__pb2.GetObjectStateReply.SerializeToString,
            ),
            'SetObjectState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectState,
                    request_deserializer=database__pb2.SetObjectStateRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'DeleteObjectState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObjectState,
                    request_deserializer=database__pb2.DeleteObjectStateRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetObjectsByState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectsByState,
                    request_deserializer=database__pb2.GetObjectsByStateRequest.FromString,
                    response_serializer=database__pb2.GetObjectsByStateReply.SerializeToString,
            ),
            'ReserveAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveAddress,
                    request_deserializer=database__pb2.ReserveAddressRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'ReleaseAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseAddress,
                    request_deserializer=database__pb2.ReleaseAddressRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=database__pb2.GetReservationRequest.FromString,
                    response_serializer=database__pb2.GetReservationReply.SerializeToString,
            ),
            'GetReservationsForIPAM': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservationsForIPAM,
                    request_deserializer=database__pb2.GetReservationsForIPAMRequest.FromString,
                    response_serializer=database__pb2.GetReservationsForIPAMReply.SerializeToString,
            ),
            'DeleteReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReservation,
                    request_deserializer=database__pb2.DeleteReservationRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'DeleteReservationsForIPAM': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReservationsForIPAM,
                    request_deserializer=database__pb2.DeleteReservationsForIPAMRequest.FromString,
                    response_serializer=database__pb2.DeleteCountReply.SerializeToString,
            ),
            'ReleaseHaloedAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseHaloedAddresses,
                    request_deserializer=database__pb2.ReleaseHaloedAddressesRequest.FromString,
                    response_serializer=database__pb2.DeleteCountReply.SerializeToString,
            ),
            'GetAddressesInUse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddressesInUse,
                    request_deserializer=database__pb2.GetAddressesInUseRequest.FromString,
                    response_serializer=database__pb2.GetAddressesInUseReply.SerializeToString,
            ),
            'CreateUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUpload,
                    request_deserializer=database__pb2.CreateUploadRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpload,
                    request_deserializer=database__pb2.GetUploadRequest.FromString,
                    response_serializer=database__pb2.GetUploadReply.SerializeToString,
            ),
            'GetUploads': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploads,
                    request_deserializer=database__pb2.GetUploadsRequest.FromString,
                    response_serializer=database__pb2.GetUploadsReply.SerializeToString,
            ),
            'DeleteUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUpload,
                    request_deserializer=database__pb2.DeleteUploadRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'UpdateUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUpload,
                    request_deserializer=database__pb2.UpdateUploadRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'CreateDnsMasq': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDnsMasq,
                    request_deserializer=database__pb2.CreateDnsMasqRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'GetDnsMasq': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDnsMasq,
                    request_deserializer=database__pb2.GetDnsMasqRequest.FromString,
                    response_serializer=database__pb2.GetDnsMasqReply.SerializeToString,
            ),
            'GetDnsMasqs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDnsMasqs,
                    request_deserializer=database__pb2.GetDnsMasqsRequest.FromString,
                    response_serializer=database__pb2.GetDnsMasqsReply.SerializeToString,
            ),
            'DeleteDnsMasq': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDnsMasq,
                    request_deserializer=database__pb2.DeleteDnsMasqRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
            'UpdateDnsMasq': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDnsMasq,
                    request_deserializer=database__pb2.UpdateDnsMasqRequest.FromString,
                    response_serializer=database__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shakenfist.protos.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shakenfist.protos.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Get',
            database__pb2.GetRequest.SerializeToString,
            database__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetPrefix',
            database__pb2.GetPrefixRequest.SerializeToString,
            database__pb2.GetPrefixReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Put',
            database__pb2.PutRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Create',
            database__pb2.CreateRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Delete',
            database__pb2.DeleteRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeletePrefix',
            database__pb2.DeletePrefixRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ReplaceMany',
            database__pb2.ReplaceManyRequest.SerializeToString,
            database__pb2.ReplaceManyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Enqueue',
            database__pb2.EnqueueRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Dequeue',
            database__pb2.DequeueRequest.SerializeToString,
            database__pb2.DequeueReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Resolve',
            database__pb2.ResolveRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetQueueLength',
            database__pb2.QueueLengthRequest.SerializeToString,
            database__pb2.QueueLengthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/RestartQueue',
            database__pb2.RestartQueueRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/AcquireLock',
            database__pb2.ClusterLockRequest.SerializeToString,
            database__pb2.ClusterLockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ReleaseLock',
            database__pb2.ClusterReleaseLockRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLockHolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetLockHolder',
            database__pb2.ClusterGetLockHolderRequest.SerializeToString,
            database__pb2.ClusterLockHolderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearStaleLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ClearStaleLocks',
            database__pb2.ClusterClearStaleLocksRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExistingLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetExistingLocks',
            database__pb2.ClusterGetExistingLocksRequest.SerializeToString,
            database__pb2.ClusterGetExistingLocksReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/Compact',
            database__pb2.CompactRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObjectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetObjectState',
            database__pb2.GetObjectStateRequest.SerializeToString,
            database__pb2.GetObjectStateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/SetObjectState',
            database__pb2.SetObjectStateRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObjectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeleteObjectState',
            database__pb2.DeleteObjectStateRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObjectsByState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetObjectsByState',
            database__pb2.GetObjectsByStateRequest.SerializeToString,
            database__pb2.GetObjectsByStateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ReserveAddress',
            database__pb2.ReserveAddressRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ReleaseAddress',
            database__pb2.ReleaseAddressRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetReservation',
            database__pb2.GetReservationRequest.SerializeToString,
            database__pb2.GetReservationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservationsForIPAM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetReservationsForIPAM',
            database__pb2.GetReservationsForIPAMRequest.SerializeToString,
            database__pb2.GetReservationsForIPAMReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeleteReservation',
            database__pb2.DeleteReservationRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReservationsForIPAM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeleteReservationsForIPAM',
            database__pb2.DeleteReservationsForIPAMRequest.SerializeToString,
            database__pb2.DeleteCountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseHaloedAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/ReleaseHaloedAddresses',
            database__pb2.ReleaseHaloedAddressesRequest.SerializeToString,
            database__pb2.DeleteCountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddressesInUse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetAddressesInUse',
            database__pb2.GetAddressesInUseRequest.SerializeToString,
            database__pb2.GetAddressesInUseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/CreateUpload',
            database__pb2.CreateUploadRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetUpload',
            database__pb2.GetUploadRequest.SerializeToString,
            database__pb2.GetUploadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetUploads',
            database__pb2.GetUploadsRequest.SerializeToString,
            database__pb2.GetUploadsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeleteUpload',
            database__pb2.DeleteUploadRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/UpdateUpload',
            database__pb2.UpdateUploadRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDnsMasq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/CreateDnsMasq',
            database__pb2.CreateDnsMasqRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDnsMasq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetDnsMasq',
            database__pb2.GetDnsMasqRequest.SerializeToString,
            database__pb2.GetDnsMasqReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDnsMasqs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/GetDnsMasqs',
            database__pb2.GetDnsMasqsRequest.SerializeToString,
            database__pb2.GetDnsMasqsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDnsMasq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/DeleteDnsMasq',
            database__pb2.DeleteDnsMasqRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDnsMasq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shakenfist.protos.DatabaseService/UpdateDnsMasq',
            database__pb2.UpdateDnsMasqRequest.SerializeToString,
            database__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
