"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
from shakenfist.protos import database_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class DatabaseServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetRequest,
        database_pb2.GetReply,
    ]
    """Key-Value Operations"""

    GetPrefix: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetPrefixRequest,
        database_pb2.GetPrefixReply,
    ]

    Put: grpc.UnaryUnaryMultiCallable[
        database_pb2.PutRequest,
        database_pb2.StatusReply,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        database_pb2.CreateRequest,
        database_pb2.StatusReply,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteRequest,
        database_pb2.StatusReply,
    ]

    DeletePrefix: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeletePrefixRequest,
        database_pb2.StatusReply,
    ]

    ReplaceMany: grpc.UnaryUnaryMultiCallable[
        database_pb2.ReplaceManyRequest,
        database_pb2.ReplaceManyReply,
    ]

    Enqueue: grpc.UnaryUnaryMultiCallable[
        database_pb2.EnqueueRequest,
        database_pb2.StatusReply,
    ]
    """Queue Operations"""

    Dequeue: grpc.UnaryUnaryMultiCallable[
        database_pb2.DequeueRequest,
        database_pb2.DequeueReply,
    ]

    Resolve: grpc.UnaryUnaryMultiCallable[
        database_pb2.ResolveRequest,
        database_pb2.StatusReply,
    ]

    GetQueueLength: grpc.UnaryUnaryMultiCallable[
        database_pb2.QueueLengthRequest,
        database_pb2.QueueLengthReply,
    ]

    RestartQueue: grpc.UnaryUnaryMultiCallable[
        database_pb2.RestartQueueRequest,
        database_pb2.StatusReply,
    ]

    AcquireLock: grpc.UnaryUnaryMultiCallable[
        database_pb2.ClusterLockRequest,
        database_pb2.ClusterLockReply,
    ]
    """Lock Operations"""

    ReleaseLock: grpc.UnaryUnaryMultiCallable[
        database_pb2.ClusterReleaseLockRequest,
        database_pb2.StatusReply,
    ]

    GetLockHolder: grpc.UnaryUnaryMultiCallable[
        database_pb2.ClusterGetLockHolderRequest,
        database_pb2.ClusterLockHolderReply,
    ]

    ClearStaleLocks: grpc.UnaryUnaryMultiCallable[
        database_pb2.ClusterClearStaleLocksRequest,
        database_pb2.StatusReply,
    ]

    GetExistingLocks: grpc.UnaryUnaryMultiCallable[
        database_pb2.ClusterGetExistingLocksRequest,
        database_pb2.ClusterGetExistingLocksReply,
    ]

    Compact: grpc.UnaryUnaryMultiCallable[
        database_pb2.CompactRequest,
        database_pb2.StatusReply,
    ]
    """Maintenance"""

    GetObjectState: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetObjectStateRequest,
        database_pb2.GetObjectStateReply,
    ]
    """Object State Operations (MariaDB)"""

    SetObjectState: grpc.UnaryUnaryMultiCallable[
        database_pb2.SetObjectStateRequest,
        database_pb2.StatusReply,
    ]

    DeleteObjectState: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteObjectStateRequest,
        database_pb2.StatusReply,
    ]

    GetObjectsByState: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetObjectsByStateRequest,
        database_pb2.GetObjectsByStateReply,
    ]

    ReserveAddress: grpc.UnaryUnaryMultiCallable[
        database_pb2.ReserveAddressRequest,
        database_pb2.StatusReply,
    ]
    """IPAM Reservation Operations (MariaDB)"""

    ReleaseAddress: grpc.UnaryUnaryMultiCallable[
        database_pb2.ReleaseAddressRequest,
        database_pb2.StatusReply,
    ]

    GetReservation: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetReservationRequest,
        database_pb2.GetReservationReply,
    ]

    GetReservationsForIPAM: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetReservationsForIPAMRequest,
        database_pb2.GetReservationsForIPAMReply,
    ]

    DeleteReservation: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteReservationRequest,
        database_pb2.StatusReply,
    ]

    DeleteReservationsForIPAM: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteReservationsForIPAMRequest,
        database_pb2.DeleteCountReply,
    ]

    ReleaseHaloedAddresses: grpc.UnaryUnaryMultiCallable[
        database_pb2.ReleaseHaloedAddressesRequest,
        database_pb2.DeleteCountReply,
    ]

    GetAddressesInUse: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetAddressesInUseRequest,
        database_pb2.GetAddressesInUseReply,
    ]

    CreateUpload: grpc.UnaryUnaryMultiCallable[
        database_pb2.CreateUploadRequest,
        database_pb2.StatusReply,
    ]
    """Upload Operations (MariaDB)"""

    GetUpload: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetUploadRequest,
        database_pb2.GetUploadReply,
    ]

    GetUploads: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetUploadsRequest,
        database_pb2.GetUploadsReply,
    ]

    DeleteUpload: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteUploadRequest,
        database_pb2.StatusReply,
    ]

    UpdateUpload: grpc.UnaryUnaryMultiCallable[
        database_pb2.UpdateUploadRequest,
        database_pb2.StatusReply,
    ]

    CreateDnsMasq: grpc.UnaryUnaryMultiCallable[
        database_pb2.CreateDnsMasqRequest,
        database_pb2.StatusReply,
    ]
    """DnsMasq Operations (MariaDB)"""

    GetDnsMasq: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetDnsMasqRequest,
        database_pb2.GetDnsMasqReply,
    ]

    GetDnsMasqs: grpc.UnaryUnaryMultiCallable[
        database_pb2.GetDnsMasqsRequest,
        database_pb2.GetDnsMasqsReply,
    ]

    DeleteDnsMasq: grpc.UnaryUnaryMultiCallable[
        database_pb2.DeleteDnsMasqRequest,
        database_pb2.StatusReply,
    ]

    UpdateDnsMasq: grpc.UnaryUnaryMultiCallable[
        database_pb2.UpdateDnsMasqRequest,
        database_pb2.StatusReply,
    ]

class DatabaseServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetRequest,
        database_pb2.GetReply,
    ]
    """Key-Value Operations"""

    GetPrefix: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetPrefixRequest,
        database_pb2.GetPrefixReply,
    ]

    Put: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.PutRequest,
        database_pb2.StatusReply,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.CreateRequest,
        database_pb2.StatusReply,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteRequest,
        database_pb2.StatusReply,
    ]

    DeletePrefix: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeletePrefixRequest,
        database_pb2.StatusReply,
    ]

    ReplaceMany: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ReplaceManyRequest,
        database_pb2.ReplaceManyReply,
    ]

    Enqueue: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.EnqueueRequest,
        database_pb2.StatusReply,
    ]
    """Queue Operations"""

    Dequeue: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DequeueRequest,
        database_pb2.DequeueReply,
    ]

    Resolve: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ResolveRequest,
        database_pb2.StatusReply,
    ]

    GetQueueLength: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.QueueLengthRequest,
        database_pb2.QueueLengthReply,
    ]

    RestartQueue: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.RestartQueueRequest,
        database_pb2.StatusReply,
    ]

    AcquireLock: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ClusterLockRequest,
        database_pb2.ClusterLockReply,
    ]
    """Lock Operations"""

    ReleaseLock: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ClusterReleaseLockRequest,
        database_pb2.StatusReply,
    ]

    GetLockHolder: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ClusterGetLockHolderRequest,
        database_pb2.ClusterLockHolderReply,
    ]

    ClearStaleLocks: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ClusterClearStaleLocksRequest,
        database_pb2.StatusReply,
    ]

    GetExistingLocks: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ClusterGetExistingLocksRequest,
        database_pb2.ClusterGetExistingLocksReply,
    ]

    Compact: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.CompactRequest,
        database_pb2.StatusReply,
    ]
    """Maintenance"""

    GetObjectState: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetObjectStateRequest,
        database_pb2.GetObjectStateReply,
    ]
    """Object State Operations (MariaDB)"""

    SetObjectState: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.SetObjectStateRequest,
        database_pb2.StatusReply,
    ]

    DeleteObjectState: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteObjectStateRequest,
        database_pb2.StatusReply,
    ]

    GetObjectsByState: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetObjectsByStateRequest,
        database_pb2.GetObjectsByStateReply,
    ]

    ReserveAddress: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ReserveAddressRequest,
        database_pb2.StatusReply,
    ]
    """IPAM Reservation Operations (MariaDB)"""

    ReleaseAddress: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ReleaseAddressRequest,
        database_pb2.StatusReply,
    ]

    GetReservation: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetReservationRequest,
        database_pb2.GetReservationReply,
    ]

    GetReservationsForIPAM: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetReservationsForIPAMRequest,
        database_pb2.GetReservationsForIPAMReply,
    ]

    DeleteReservation: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteReservationRequest,
        database_pb2.StatusReply,
    ]

    DeleteReservationsForIPAM: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteReservationsForIPAMRequest,
        database_pb2.DeleteCountReply,
    ]

    ReleaseHaloedAddresses: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.ReleaseHaloedAddressesRequest,
        database_pb2.DeleteCountReply,
    ]

    GetAddressesInUse: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetAddressesInUseRequest,
        database_pb2.GetAddressesInUseReply,
    ]

    CreateUpload: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.CreateUploadRequest,
        database_pb2.StatusReply,
    ]
    """Upload Operations (MariaDB)"""

    GetUpload: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetUploadRequest,
        database_pb2.GetUploadReply,
    ]

    GetUploads: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetUploadsRequest,
        database_pb2.GetUploadsReply,
    ]

    DeleteUpload: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteUploadRequest,
        database_pb2.StatusReply,
    ]

    UpdateUpload: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.UpdateUploadRequest,
        database_pb2.StatusReply,
    ]

    CreateDnsMasq: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.CreateDnsMasqRequest,
        database_pb2.StatusReply,
    ]
    """DnsMasq Operations (MariaDB)"""

    GetDnsMasq: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetDnsMasqRequest,
        database_pb2.GetDnsMasqReply,
    ]

    GetDnsMasqs: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.GetDnsMasqsRequest,
        database_pb2.GetDnsMasqsReply,
    ]

    DeleteDnsMasq: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.DeleteDnsMasqRequest,
        database_pb2.StatusReply,
    ]

    UpdateDnsMasq: grpc.aio.UnaryUnaryMultiCallable[
        database_pb2.UpdateDnsMasqRequest,
        database_pb2.StatusReply,
    ]

class DatabaseServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: database_pb2.GetRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetReply, collections.abc.Awaitable[database_pb2.GetReply]]:
        """Key-Value Operations"""

    @abc.abstractmethod
    def GetPrefix(
        self,
        request: database_pb2.GetPrefixRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetPrefixReply, collections.abc.Awaitable[database_pb2.GetPrefixReply]]: ...

    @abc.abstractmethod
    def Put(
        self,
        request: database_pb2.PutRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: database_pb2.CreateRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: database_pb2.DeleteRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def DeletePrefix(
        self,
        request: database_pb2.DeletePrefixRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def ReplaceMany(
        self,
        request: database_pb2.ReplaceManyRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.ReplaceManyReply, collections.abc.Awaitable[database_pb2.ReplaceManyReply]]: ...

    @abc.abstractmethod
    def Enqueue(
        self,
        request: database_pb2.EnqueueRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]:
        """Queue Operations"""

    @abc.abstractmethod
    def Dequeue(
        self,
        request: database_pb2.DequeueRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.DequeueReply, collections.abc.Awaitable[database_pb2.DequeueReply]]: ...

    @abc.abstractmethod
    def Resolve(
        self,
        request: database_pb2.ResolveRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def GetQueueLength(
        self,
        request: database_pb2.QueueLengthRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.QueueLengthReply, collections.abc.Awaitable[database_pb2.QueueLengthReply]]: ...

    @abc.abstractmethod
    def RestartQueue(
        self,
        request: database_pb2.RestartQueueRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def AcquireLock(
        self,
        request: database_pb2.ClusterLockRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.ClusterLockReply, collections.abc.Awaitable[database_pb2.ClusterLockReply]]:
        """Lock Operations"""

    @abc.abstractmethod
    def ReleaseLock(
        self,
        request: database_pb2.ClusterReleaseLockRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def GetLockHolder(
        self,
        request: database_pb2.ClusterGetLockHolderRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.ClusterLockHolderReply, collections.abc.Awaitable[database_pb2.ClusterLockHolderReply]]: ...

    @abc.abstractmethod
    def ClearStaleLocks(
        self,
        request: database_pb2.ClusterClearStaleLocksRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def GetExistingLocks(
        self,
        request: database_pb2.ClusterGetExistingLocksRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.ClusterGetExistingLocksReply, collections.abc.Awaitable[database_pb2.ClusterGetExistingLocksReply]]: ...

    @abc.abstractmethod
    def Compact(
        self,
        request: database_pb2.CompactRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]:
        """Maintenance"""

    @abc.abstractmethod
    def GetObjectState(
        self,
        request: database_pb2.GetObjectStateRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetObjectStateReply, collections.abc.Awaitable[database_pb2.GetObjectStateReply]]:
        """Object State Operations (MariaDB)"""

    @abc.abstractmethod
    def SetObjectState(
        self,
        request: database_pb2.SetObjectStateRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def DeleteObjectState(
        self,
        request: database_pb2.DeleteObjectStateRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def GetObjectsByState(
        self,
        request: database_pb2.GetObjectsByStateRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetObjectsByStateReply, collections.abc.Awaitable[database_pb2.GetObjectsByStateReply]]: ...

    @abc.abstractmethod
    def ReserveAddress(
        self,
        request: database_pb2.ReserveAddressRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]:
        """IPAM Reservation Operations (MariaDB)"""

    @abc.abstractmethod
    def ReleaseAddress(
        self,
        request: database_pb2.ReleaseAddressRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def GetReservation(
        self,
        request: database_pb2.GetReservationRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetReservationReply, collections.abc.Awaitable[database_pb2.GetReservationReply]]: ...

    @abc.abstractmethod
    def GetReservationsForIPAM(
        self,
        request: database_pb2.GetReservationsForIPAMRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetReservationsForIPAMReply, collections.abc.Awaitable[database_pb2.GetReservationsForIPAMReply]]: ...

    @abc.abstractmethod
    def DeleteReservation(
        self,
        request: database_pb2.DeleteReservationRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def DeleteReservationsForIPAM(
        self,
        request: database_pb2.DeleteReservationsForIPAMRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.DeleteCountReply, collections.abc.Awaitable[database_pb2.DeleteCountReply]]: ...

    @abc.abstractmethod
    def ReleaseHaloedAddresses(
        self,
        request: database_pb2.ReleaseHaloedAddressesRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.DeleteCountReply, collections.abc.Awaitable[database_pb2.DeleteCountReply]]: ...

    @abc.abstractmethod
    def GetAddressesInUse(
        self,
        request: database_pb2.GetAddressesInUseRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetAddressesInUseReply, collections.abc.Awaitable[database_pb2.GetAddressesInUseReply]]: ...

    @abc.abstractmethod
    def CreateUpload(
        self,
        request: database_pb2.CreateUploadRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]:
        """Upload Operations (MariaDB)"""

    @abc.abstractmethod
    def GetUpload(
        self,
        request: database_pb2.GetUploadRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetUploadReply, collections.abc.Awaitable[database_pb2.GetUploadReply]]: ...

    @abc.abstractmethod
    def GetUploads(
        self,
        request: database_pb2.GetUploadsRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetUploadsReply, collections.abc.Awaitable[database_pb2.GetUploadsReply]]: ...

    @abc.abstractmethod
    def DeleteUpload(
        self,
        request: database_pb2.DeleteUploadRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def UpdateUpload(
        self,
        request: database_pb2.UpdateUploadRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def CreateDnsMasq(
        self,
        request: database_pb2.CreateDnsMasqRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]:
        """DnsMasq Operations (MariaDB)"""

    @abc.abstractmethod
    def GetDnsMasq(
        self,
        request: database_pb2.GetDnsMasqRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetDnsMasqReply, collections.abc.Awaitable[database_pb2.GetDnsMasqReply]]: ...

    @abc.abstractmethod
    def GetDnsMasqs(
        self,
        request: database_pb2.GetDnsMasqsRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.GetDnsMasqsReply, collections.abc.Awaitable[database_pb2.GetDnsMasqsReply]]: ...

    @abc.abstractmethod
    def DeleteDnsMasq(
        self,
        request: database_pb2.DeleteDnsMasqRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

    @abc.abstractmethod
    def UpdateDnsMasq(
        self,
        request: database_pb2.UpdateDnsMasqRequest,
        context: _ServicerContext,
    ) -> typing.Union[database_pb2.StatusReply, collections.abc.Awaitable[database_pb2.StatusReply]]: ...

def add_DatabaseServiceServicer_to_server(servicer: DatabaseServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
