"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EventRequest(google.protobuf.message.Message):
    """An event against a single object, should be removed one day"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_UUID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    OBSOLETE_TIMESTAMP_FIELD_NUMBER: builtins.int
    FQDN_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    object_uuid: builtins.str
    event_type: builtins.str
    obsolete_timestamp: builtins.float
    fqdn: builtins.str
    duration: builtins.float
    message: builtins.str
    extra: builtins.str
    timestamp: builtins.float
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        object_uuid: builtins.str = ...,
        event_type: builtins.str = ...,
        obsolete_timestamp: builtins.float | None = ...,
        fqdn: builtins.str = ...,
        duration: builtins.float = ...,
        message: builtins.str = ...,
        extra: builtins.str = ...,
        timestamp: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_obsolete_timestamp", b"_obsolete_timestamp", "obsolete_timestamp", b"obsolete_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_obsolete_timestamp", b"_obsolete_timestamp", "duration", b"duration", "event_type", b"event_type", "extra", b"extra", "fqdn", b"fqdn", "message", b"message", "object_type", b"object_type", "object_uuid", b"object_uuid", "obsolete_timestamp", b"obsolete_timestamp", "timestamp", b"timestamp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_obsolete_timestamp", b"_obsolete_timestamp"]) -> typing.Literal["obsolete_timestamp"] | None: ...

global___EventRequest = EventRequest

@typing.final
class EventObject(google.protobuf.message.Message):
    """An event against multiple objects"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_UUID_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    object_uuid: builtins.str
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        object_uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_type", b"object_type", "object_uuid", b"object_uuid"]) -> None: ...

global___EventObject = EventObject

@typing.final
class EventMultiRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECTS_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    FQDN_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    event_type: builtins.str
    fqdn: builtins.str
    duration: builtins.float
    message: builtins.str
    extra: builtins.str
    timestamp: builtins.float
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventObject]: ...
    def __init__(
        self,
        *,
        objects: collections.abc.Iterable[global___EventObject] | None = ...,
        event_type: builtins.str = ...,
        fqdn: builtins.str = ...,
        duration: builtins.float | None = ...,
        message: builtins.str = ...,
        extra: builtins.str = ...,
        timestamp: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_duration", b"_duration", "duration", b"duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_duration", b"_duration", "duration", b"duration", "event_type", b"event_type", "extra", b"extra", "fqdn", b"fqdn", "message", b"message", "objects", b"objects", "timestamp", b"timestamp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_duration", b"_duration"]) -> typing.Literal["duration"] | None: ...

global___EventMultiRequest = EventMultiRequest

@typing.final
class EventMultiBatchRequest(google.protobuf.message.Message):
    """Batched submission of multiple ``EventMultiRequest`` items in a
    single RPC. The eventlog daemon persists the whole batch in one
    transaction; either all succeed or none do. Used by the local
    eventlog spool drainer to amortise the per-event RPC cost; sized
    at ~100 events per batch by the caller.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventMultiRequest]: ...
    def __init__(
        self,
        *,
        events: collections.abc.Iterable[global___EventMultiRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events", b"events"]) -> None: ...

global___EventMultiBatchRequest = EventMultiBatchRequest

@typing.final
class EventReply(google.protobuf.message.Message):
    """An ack from the eventlog daemon"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    ack: builtins.bool
    def __init__(
        self,
        *,
        ack: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ack", b"ack"]) -> None: ...

global___EventReply = EventReply
