"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
from shakenfist.protos import event_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class EventServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    RecordEvent: grpc.UnaryUnaryMultiCallable[
        event_pb2.EventRequest,
        event_pb2.EventReply,
    ]

    RecordMultiEvent: grpc.UnaryUnaryMultiCallable[
        event_pb2.EventMultiRequest,
        event_pb2.EventReply,
    ]

class EventServiceAsyncStub:
    RecordEvent: grpc.aio.UnaryUnaryMultiCallable[
        event_pb2.EventRequest,
        event_pb2.EventReply,
    ]

    RecordMultiEvent: grpc.aio.UnaryUnaryMultiCallable[
        event_pb2.EventMultiRequest,
        event_pb2.EventReply,
    ]

class EventServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def RecordEvent(
        self,
        request: event_pb2.EventRequest,
        context: _ServicerContext,
    ) -> typing.Union[event_pb2.EventReply, collections.abc.Awaitable[event_pb2.EventReply]]: ...

    @abc.abstractmethod
    def RecordMultiEvent(
        self,
        request: event_pb2.EventMultiRequest,
        context: _ServicerContext,
    ) -> typing.Union[event_pb2.EventReply, collections.abc.Awaitable[event_pb2.EventReply]]: ...

def add_EventServiceServicer_to_server(servicer: EventServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
