"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
from shakenfist.protos import common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _HashAlgorithm:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HashAlgorithmEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HashAlgorithm.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHA1: _HashAlgorithm.ValueType  # 0
    SHA256: _HashAlgorithm.ValueType  # 1
    SHA512: _HashAlgorithm.ValueType  # 2
    XXH128: _HashAlgorithm.ValueType  # 3

class HashAlgorithm(_HashAlgorithm, metaclass=_HashAlgorithmEnumTypeWrapper): ...

SHA1: HashAlgorithm.ValueType  # 0
SHA256: HashAlgorithm.ValueType  # 1
SHA512: HashAlgorithm.ValueType  # 2
XXH128: HashAlgorithm.ValueType  # 3
global___HashAlgorithm = HashAlgorithm

@typing.final
class HashFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    ALGORITHM_FIELD_NUMBER: builtins.int
    path: builtins.str
    algorithm: global___HashAlgorithm.ValueType
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        algorithm: global___HashAlgorithm.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm", "path", b"path"]) -> None: ...

global___HashFileRequest = HashFileRequest

@typing.final
class HashFileReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HashFileReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: HashFileReply._Errors.ValueType  # 0
        FILE_NOT_FOUND: HashFileReply._Errors.ValueType  # 1
        UNKNOWN_ALGORITHM: HashFileReply._Errors.ValueType  # 2
        ALGORITHM_NOT_FOUND: HashFileReply._Errors.ValueType  # 3
        ALGORITHM_FAILED: HashFileReply._Errors.ValueType  # 4

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: HashFileReply.Errors.ValueType  # 0
    FILE_NOT_FOUND: HashFileReply.Errors.ValueType  # 1
    UNKNOWN_ALGORITHM: HashFileReply.Errors.ValueType  # 2
    ALGORITHM_NOT_FOUND: HashFileReply.Errors.ValueType  # 3
    ALGORITHM_FAILED: HashFileReply.Errors.ValueType  # 4

    PATH_FIELD_NUMBER: builtins.int
    ALGORITHM_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    path: builtins.str
    algorithm: global___HashAlgorithm.ValueType
    hash: builtins.str
    error: global___HashFileReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        algorithm: global___HashAlgorithm.ValueType = ...,
        hash: builtins.str = ...,
        error: global___HashFileReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm", "error", b"error", "error_text", b"error_text", "hash", b"hash", "path", b"path"]) -> None: ...

global___HashFileReply = HashFileReply

@typing.final
class EnableNATRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    NETWORK_ADDRESS_FIELD_NUMBER: builtins.int
    NETWORK_MASK_FIELD_NUMBER: builtins.int
    VXID_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    network_address: builtins.str
    network_mask: builtins.str
    vxid: builtins.int
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        network_address: builtins.str = ...,
        network_mask: builtins.str = ...,
        vxid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["network_address", b"network_address", "network_mask", b"network_mask", "network_uuid", b"network_uuid", "vxid", b"vxid"]) -> None: ...

global___EnableNATRequest = EnableNATRequest

@typing.final
class EnableNATReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EnableNATReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: EnableNATReply._Errors.ValueType  # 0
        IPTABLES_FAILED: EnableNATReply._Errors.ValueType  # 1
        RULES_ALREADY_PRESENT: EnableNATReply._Errors.ValueType  # 2

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: EnableNATReply.Errors.ValueType  # 0
    IPTABLES_FAILED: EnableNATReply.Errors.ValueType  # 1
    RULES_ALREADY_PRESENT: EnableNATReply.Errors.ValueType  # 2

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    NETWORK_ADDRESS_FIELD_NUMBER: builtins.int
    NETWORK_MASK_FIELD_NUMBER: builtins.int
    VXID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    network_address: builtins.str
    network_mask: builtins.str
    vxid: builtins.int
    error: global___EnableNATReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        network_address: builtins.str = ...,
        network_mask: builtins.str = ...,
        vxid: builtins.int = ...,
        error: global___EnableNATReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_text", b"error_text", "network_address", b"network_address", "network_mask", b"network_mask", "network_uuid", b"network_uuid", "vxid", b"vxid"]) -> None: ...

global___EnableNATReply = EnableNATReply

@typing.final
class EnsureVXLANMeshRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    VXID_FIELD_NUMBER: builtins.int
    NODE_IPS_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    vxid: builtins.int
    @property
    def node_ips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        vxid: builtins.int = ...,
        node_ips: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["network_uuid", b"network_uuid", "node_ips", b"node_ips", "vxid", b"vxid"]) -> None: ...

global___EnsureVXLANMeshRequest = EnsureVXLANMeshRequest

@typing.final
class EnsureVXLANMeshReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EnsureVXLANMeshReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: EnsureVXLANMeshReply._Errors.ValueType  # 0
        FAILURE: EnsureVXLANMeshReply._Errors.ValueType  # 1

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: EnsureVXLANMeshReply.Errors.ValueType  # 0
    FAILURE: EnsureVXLANMeshReply.Errors.ValueType  # 1

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    VXID_FIELD_NUMBER: builtins.int
    ADDED_ADDRESSES_FIELD_NUMBER: builtins.int
    REMOVED_ADDRESSES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    vxid: builtins.int
    error: global___EnsureVXLANMeshReply.Errors.ValueType
    error_text: builtins.str
    @property
    def added_addresses(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def removed_addresses(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        vxid: builtins.int = ...,
        added_addresses: collections.abc.Iterable[builtins.str] | None = ...,
        removed_addresses: collections.abc.Iterable[builtins.str] | None = ...,
        error: global___EnsureVXLANMeshReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["added_addresses", b"added_addresses", "error", b"error", "error_text", b"error_text", "network_uuid", b"network_uuid", "removed_addresses", b"removed_addresses", "vxid", b"vxid"]) -> None: ...

global___EnsureVXLANMeshReply = EnsureVXLANMeshReply

@typing.final
class AddFloatingIPRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    FLOATING_ADDRESS_FIELD_NUMBER: builtins.int
    INNER_ADDRESS_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    floating_address: builtins.str
    inner_address: builtins.str
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        floating_address: builtins.str = ...,
        inner_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["floating_address", b"floating_address", "inner_address", b"inner_address", "network_uuid", b"network_uuid"]) -> None: ...

global___AddFloatingIPRequest = AddFloatingIPRequest

@typing.final
class AddFloatingIPReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AddFloatingIPReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: AddFloatingIPReply._Errors.ValueType  # 0
        CREATE_INTERFACE_FAILED: AddFloatingIPReply._Errors.ValueType  # 1
        ADD_ADDRESS_FAILED: AddFloatingIPReply._Errors.ValueType  # 2
        IPTABLES_FAILED: AddFloatingIPReply._Errors.ValueType  # 3

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: AddFloatingIPReply.Errors.ValueType  # 0
    CREATE_INTERFACE_FAILED: AddFloatingIPReply.Errors.ValueType  # 1
    ADD_ADDRESS_FAILED: AddFloatingIPReply.Errors.ValueType  # 2
    IPTABLES_FAILED: AddFloatingIPReply.Errors.ValueType  # 3

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    FLOATING_ADDRESS_FIELD_NUMBER: builtins.int
    INNER_ADDRESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    floating_address: builtins.str
    inner_address: builtins.str
    error: global___AddFloatingIPReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        floating_address: builtins.str = ...,
        inner_address: builtins.str = ...,
        error: global___AddFloatingIPReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_text", b"error_text", "floating_address", b"floating_address", "inner_address", b"inner_address", "network_uuid", b"network_uuid"]) -> None: ...

global___AddFloatingIPReply = AddFloatingIPReply

@typing.final
class RemoveFloatingIPRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    FLOATING_ADDRESS_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    floating_address: builtins.str
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        floating_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["floating_address", b"floating_address", "network_uuid", b"network_uuid"]) -> None: ...

global___RemoveFloatingIPRequest = RemoveFloatingIPRequest

@typing.final
class RemoveFloatingIPReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoveFloatingIPReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: RemoveFloatingIPReply._Errors.ValueType  # 0
        FAILED: RemoveFloatingIPReply._Errors.ValueType  # 1

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: RemoveFloatingIPReply.Errors.ValueType  # 0
    FAILED: RemoveFloatingIPReply.Errors.ValueType  # 1

    NETWORK_UUID_FIELD_NUMBER: builtins.int
    FLOATING_ADDRESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    network_uuid: builtins.str
    floating_address: builtins.str
    error: global___RemoveFloatingIPReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        network_uuid: builtins.str = ...,
        floating_address: builtins.str = ...,
        error: global___RemoveFloatingIPReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_text", b"error_text", "floating_address", b"floating_address", "network_uuid", b"network_uuid"]) -> None: ...

global___RemoveFloatingIPReply = RemoveFloatingIPReply

@typing.final
class CreateVXLANInterfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VX_ID_FIELD_NUMBER: builtins.int
    MESH_INTERFACE_FIELD_NUMBER: builtins.int
    vx_id: builtins.int
    mesh_interface: builtins.str
    def __init__(
        self,
        *,
        vx_id: builtins.int = ...,
        mesh_interface: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mesh_interface", b"mesh_interface", "vx_id", b"vx_id"]) -> None: ...

global___CreateVXLANInterfaceRequest = CreateVXLANInterfaceRequest

@typing.final
class CreateVXLANInterfaceReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CreateVXLANInterfaceReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: CreateVXLANInterfaceReply._Errors.ValueType  # 0
        FAILED: CreateVXLANInterfaceReply._Errors.ValueType  # 1

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: CreateVXLANInterfaceReply.Errors.ValueType  # 0
    FAILED: CreateVXLANInterfaceReply.Errors.ValueType  # 1

    VX_ID_FIELD_NUMBER: builtins.int
    MESH_INTERFACE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    vx_id: builtins.int
    mesh_interface: builtins.str
    error: global___CreateVXLANInterfaceReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        vx_id: builtins.int = ...,
        mesh_interface: builtins.str = ...,
        error: global___CreateVXLANInterfaceReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_text", b"error_text", "mesh_interface", b"mesh_interface", "vx_id", b"vx_id"]) -> None: ...

global___CreateVXLANInterfaceReply = CreateVXLANInterfaceReply

@typing.final
class CreateNetworkNamespaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["namespace", b"namespace"]) -> None: ...

global___CreateNetworkNamespaceRequest = CreateNetworkNamespaceRequest

@typing.final
class CreateNetworkNamespaceReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Errors:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CreateNetworkNamespaceReply._Errors.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: CreateNetworkNamespaceReply._Errors.ValueType  # 0
        FAILED: CreateNetworkNamespaceReply._Errors.ValueType  # 1

    class Errors(_Errors, metaclass=_ErrorsEnumTypeWrapper): ...
    OK: CreateNetworkNamespaceReply.Errors.ValueType  # 0
    FAILED: CreateNetworkNamespaceReply.Errors.ValueType  # 1

    NAMESPACE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_TEXT_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    error: global___CreateNetworkNamespaceReply.Errors.ValueType
    error_text: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        error: global___CreateNetworkNamespaceReply.Errors.ValueType = ...,
        error_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_text", b"error_text", "namespace", b"namespace"]) -> None: ...

global___CreateNetworkNamespaceReply = CreateNetworkNamespaceReply

@typing.final
class PrivExecRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTE_REQUEST_FIELD_NUMBER: builtins.int
    HASH_FILE_REQUEST_FIELD_NUMBER: builtins.int
    ENABLE_NAT_REQUEST_FIELD_NUMBER: builtins.int
    ENSURE_VXLAN_MESH_REQUEST_FIELD_NUMBER: builtins.int
    ADD_FLOATING_IP_REQUEST_FIELD_NUMBER: builtins.int
    REMOVE_FLOATING_IP_REQUEST_FIELD_NUMBER: builtins.int
    CREATE_VXLAN_INTERFACE_REQUEST_FIELD_NUMBER: builtins.int
    CREATE_NETWORK_NAMESPACE_REQUEST_FIELD_NUMBER: builtins.int
    @property
    def execute_request(self) -> common_pb2.ExecuteRequest: ...
    @property
    def hash_file_request(self) -> global___HashFileRequest: ...
    @property
    def enable_nat_request(self) -> global___EnableNATRequest: ...
    @property
    def ensure_vxlan_mesh_request(self) -> global___EnsureVXLANMeshRequest: ...
    @property
    def add_floating_ip_request(self) -> global___AddFloatingIPRequest: ...
    @property
    def remove_floating_ip_request(self) -> global___RemoveFloatingIPRequest: ...
    @property
    def create_vxlan_interface_request(self) -> global___CreateVXLANInterfaceRequest: ...
    @property
    def create_network_namespace_request(self) -> global___CreateNetworkNamespaceRequest: ...
    def __init__(
        self,
        *,
        execute_request: common_pb2.ExecuteRequest | None = ...,
        hash_file_request: global___HashFileRequest | None = ...,
        enable_nat_request: global___EnableNATRequest | None = ...,
        ensure_vxlan_mesh_request: global___EnsureVXLANMeshRequest | None = ...,
        add_floating_ip_request: global___AddFloatingIPRequest | None = ...,
        remove_floating_ip_request: global___RemoveFloatingIPRequest | None = ...,
        create_vxlan_interface_request: global___CreateVXLANInterfaceRequest | None = ...,
        create_network_namespace_request: global___CreateNetworkNamespaceRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["add_floating_ip_request", b"add_floating_ip_request", "create_network_namespace_request", b"create_network_namespace_request", "create_vxlan_interface_request", b"create_vxlan_interface_request", "enable_nat_request", b"enable_nat_request", "ensure_vxlan_mesh_request", b"ensure_vxlan_mesh_request", "execute_request", b"execute_request", "hash_file_request", b"hash_file_request", "remove_floating_ip_request", b"remove_floating_ip_request", "request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["add_floating_ip_request", b"add_floating_ip_request", "create_network_namespace_request", b"create_network_namespace_request", "create_vxlan_interface_request", b"create_vxlan_interface_request", "enable_nat_request", b"enable_nat_request", "ensure_vxlan_mesh_request", b"ensure_vxlan_mesh_request", "execute_request", b"execute_request", "hash_file_request", b"hash_file_request", "remove_floating_ip_request", b"remove_floating_ip_request", "request", b"request"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["request", b"request"]) -> typing.Literal["execute_request", "hash_file_request", "enable_nat_request", "ensure_vxlan_mesh_request", "add_floating_ip_request", "remove_floating_ip_request", "create_vxlan_interface_request", "create_network_namespace_request"] | None: ...

global___PrivExecRequest = PrivExecRequest

@typing.final
class PrivExecReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTE_REPLY_FIELD_NUMBER: builtins.int
    HASH_FILE_REPLY_FIELD_NUMBER: builtins.int
    ENABLE_NAT_REPLY_FIELD_NUMBER: builtins.int
    ENSURE_VXLAN_MESH_REPLY_FIELD_NUMBER: builtins.int
    ADD_FLOATING_IP_REPLY_FIELD_NUMBER: builtins.int
    REMOVE_FLOATING_IP_REPLY_FIELD_NUMBER: builtins.int
    CREATE_VXLAN_INTERFACE_REPLY_FIELD_NUMBER: builtins.int
    CREATE_NETWORK_NAMESPACE_REPLY_FIELD_NUMBER: builtins.int
    @property
    def execute_reply(self) -> common_pb2.ExecuteReply: ...
    @property
    def hash_file_reply(self) -> global___HashFileReply: ...
    @property
    def enable_nat_reply(self) -> global___EnableNATReply: ...
    @property
    def ensure_vxlan_mesh_reply(self) -> global___EnsureVXLANMeshReply: ...
    @property
    def add_floating_ip_reply(self) -> global___AddFloatingIPReply: ...
    @property
    def remove_floating_ip_reply(self) -> global___RemoveFloatingIPReply: ...
    @property
    def create_vxlan_interface_reply(self) -> global___CreateVXLANInterfaceReply: ...
    @property
    def create_network_namespace_reply(self) -> global___CreateNetworkNamespaceReply: ...
    def __init__(
        self,
        *,
        execute_reply: common_pb2.ExecuteReply | None = ...,
        hash_file_reply: global___HashFileReply | None = ...,
        enable_nat_reply: global___EnableNATReply | None = ...,
        ensure_vxlan_mesh_reply: global___EnsureVXLANMeshReply | None = ...,
        add_floating_ip_reply: global___AddFloatingIPReply | None = ...,
        remove_floating_ip_reply: global___RemoveFloatingIPReply | None = ...,
        create_vxlan_interface_reply: global___CreateVXLANInterfaceReply | None = ...,
        create_network_namespace_reply: global___CreateNetworkNamespaceReply | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["add_floating_ip_reply", b"add_floating_ip_reply", "create_network_namespace_reply", b"create_network_namespace_reply", "create_vxlan_interface_reply", b"create_vxlan_interface_reply", "enable_nat_reply", b"enable_nat_reply", "ensure_vxlan_mesh_reply", b"ensure_vxlan_mesh_reply", "execute_reply", b"execute_reply", "hash_file_reply", b"hash_file_reply", "remove_floating_ip_reply", b"remove_floating_ip_reply", "reply", b"reply"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["add_floating_ip_reply", b"add_floating_ip_reply", "create_network_namespace_reply", b"create_network_namespace_reply", "create_vxlan_interface_reply", b"create_vxlan_interface_reply", "enable_nat_reply", b"enable_nat_reply", "ensure_vxlan_mesh_reply", b"ensure_vxlan_mesh_reply", "execute_reply", b"execute_reply", "hash_file_reply", b"hash_file_reply", "remove_floating_ip_reply", b"remove_floating_ip_reply", "reply", b"reply"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["reply", b"reply"]) -> typing.Literal["execute_reply", "hash_file_reply", "enable_nat_reply", "ensure_vxlan_mesh_reply", "add_floating_ip_reply", "remove_floating_ip_reply", "create_vxlan_interface_reply", "create_network_namespace_reply"] | None: ...

global___PrivExecReply = PrivExecReply
