# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shakenfist_enums.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shakenfist_enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16shakenfist_enums.proto\x12\x11shakenfist.protos*\xdb\x06\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aOBJECT_TYPE_AGENTOPERATION\x10\x01\x12\x18\n\x14OBJECT_TYPE_ARTIFACT\x10\x02\x12\x14\n\x10OBJECT_TYPE_BLOB\x10\x03\x12\x14\n\x10OBJECT_TYPE_DHCP\x10\x04\x12\x18\n\x14OBJECT_TYPE_INSTANCE\x10\x05\x12\x19\n\x15OBJECT_TYPE_INTERFACE\x10\x06\x12\x14\n\x10OBJECT_TYPE_IPAM\x10\x07\x12\x19\n\x15OBJECT_TYPE_NAMESPACE\x10\x08\x12\x17\n\x13OBJECT_TYPE_NETWORK\x10\t\x12\x14\n\x10OBJECT_TYPE_NODE\x10\n\x12\x16\n\x12OBJECT_TYPE_UPLOAD\x10\x0b\x12!\n\x1dOBJECT_TYPE_ARTIFACT_FETCH_OP\x10\x0c\x12\x1b\n\x17OBJECT_TYPE_IMGCACHE_OP\x10\r\x12\x1c\n\x18OBJECT_TYPE_NET_IFACE_OP\x10\x0e\x12\x1f\n\x1bOBJECT_TYPE_NET_IFACE_IP_OP\x10\x0f\x12\x19\n\x15OBJECT_TYPE_NET_IP_OP\x10\x10\x12!\n\x1dOBJECT_TYPE_NET_MACADDR_IP_OP\x10\x11\x12\x16\n\x12OBJECT_TYPE_NET_OP\x10\x12\x12\x1b\n\x17OBJECT_TYPE_NODE_AOP_OP\x10\x13\x12\x1c\n\x18OBJECT_TYPE_NODE_BLOB_OP\x10\x14\x12&\n\"OBJECT_TYPE_NODE_INST_NET_IFACE_OP\x10\x15\x12$\n OBJECT_TYPE_NODE_INST_NETDESC_OP\x10\x16\x12\x1c\n\x18OBJECT_TYPE_NODE_INST_OP\x10\x17\x12!\n\x1dOBJECT_TYPE_NODE_INST_SNAP_OP\x10\x18\x12\x1b\n\x17OBJECT_TYPE_NODE_NET_OP\x10\x19\x12\x1c\n\x18OBJECT_TYPE_API_REQUESTS\x10\x1a\x12\x17\n\x13OBJECT_TYPE_UNKNOWN\x10\x1b\x12*\n&OBJECT_TYPE_UNKNOWN_MANAGED_EXECUTABLE\x10\x1c*\xac\x02\n\x0fReservationType\x12 \n\x1cRESERVATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18RESERVATION_TYPE_NETWORK\x10\x01\x12\x1e\n\x1aRESERVATION_TYPE_BROADCAST\x10\x02\x12\x1c\n\x18RESERVATION_TYPE_GATEWAY\x10\x03\x12\x1d\n\x19RESERVATION_TYPE_FLOATING\x10\x04\x12\x1b\n\x17RESERVATION_TYPE_ROUTED\x10\x05\x12\x1d\n\x19RESERVATION_TYPE_INSTANCE\x10\x06\x12\"\n\x1eRESERVATION_TYPE_DELETION_HALO\x10\x07\x12\x1c\n\x18RESERVATION_TYPE_UNKNOWN\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shakenfist_enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTTYPE']._serialized_start=46
  _globals['_OBJECTTYPE']._serialized_end=905
  _globals['_RESERVATIONTYPE']._serialized_start=908
  _globals['_RESERVATIONTYPE']._serialized_end=1208
# @@protoc_insertion_point(module_scope)
