"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Auto-generated by _generate_enums.py - DO NOT EDIT

This file is generated from Python enum definitions in
shakenfist/schema/. To regenerate:

  cd protos
  python3 _generate_enums.py > shakenfist_enums.proto

Source of truth: schema/object_types.py
                 schema/ipam_reservation.py
                 schema/relationship_types.py
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...
