- name: Deploy infrastructure
  terraform:
    project_path: ./terraform/aws-single-node
    state: present
    force_init: true
    variables:
      ssh_key: "{{ssh_key}}"
  register: terraform_out

- name: Add sf-single to ansible
  add_host:
    hostname: sf-single
    ansible_ssh_host: "{{terraform_out.outputs.sf_single_external.value}}"
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "{{ssh_key}}"
    groups:
      - hypervisors
      - db

- name: Add sf-single node_ip
  set_fact:
    node_ip: "{{terraform_out.outputs.sf_single_internal.value}}"
  delegate_to: sf-single
  delegate_facts: true

- name: Log terraform hosts
  debug:
    msg:
      - "sf-single: {{hostvars['sf-single']['ansible_ssh_host']}}, {{hostvars['sf-single']['node_ip']}}"
