- name: Deploy infrastructure
  terraform:
    project_path: "{{ansible_root}}/terraform/gcp-xl"
    state: present
    force_init: true
    variables:
      project: "{{project}}"
      uniqifier: "{{uniqifier}}"
      ssh_user: "{{ssh_user}}"
      ssh_key: "{{ssh_key}}"
      node_count: 10
      node_image: "sf-debian-10-20210215"
  register: terraform_out

- name: Determine node_ip for the primary node
  shell: ip addr | grep "inet 10" | sed -e 's/.*inet //' -e 's/\/32.*//'
  register: primary_ip_complex
  ignore_errors: True

- name: Add localhost to the right groups
  add_host:
    hostname: localhost
    groups: primary

- name: Set primary node_ip
  set_fact:
    node_ip: "{{primary_ip_complex.stdout}}"
    primary_node_ip: "{{primary_ip_complex.stdout}}"
  delegate_to: localhost
  delegate_facts: true

- name: Add sf nodes
  add_host:
    hostname: "sf-{{node_idx + 1}}"
    node_name: "sf-{{node_idx + 1}}"
    ansible_ssh_host: "{{item}}"
    node_ip: "{{item}}"
    ansible_ssh_private_key_file: "{{ssh_key_filename|default(omit)}}"
    groups: hypervisors
  loop: "{{terraform_out.outputs.sf_nodes_external_ip.value}}"
  loop_control:
    index_var: node_idx

- name: Add sf-1 as an etcd master
  add_host:
    hostname: "sf-1"
    groups: hypervisors, etcd_master

- name: Add sf-2 as an etcd master
  add_host:
    hostname: "sf-2"
    groups: hypervisors, etcd_master

- name: Add sf-3 as an etcd master
  add_host:
    hostname: "sf-3"
    groups: hypervisors, etcd_master

- name: Log terraform hosts
  debug:
    msg:
      - "sf-1: {{hostvars['sf-1']['ansible_ssh_host']}}, {{hostvars['sf-1']['node_ip']}}"
      - "sf-2: {{hostvars['sf-2']['ansible_ssh_host']}}, {{hostvars['sf-2']['node_ip']}}"
      - "sf-3: {{hostvars['sf-3']['ansible_ssh_host']}}, {{hostvars['sf-3']['node_ip']}}"
      - "sf-4: {{hostvars['sf-4']['ansible_ssh_host']}}, {{hostvars['sf-4']['node_ip']}}"
      - "sf-5: {{hostvars['sf-5']['ansible_ssh_host']}}, {{hostvars['sf-5']['node_ip']}}"
      - "sf-6: {{hostvars['sf-6']['ansible_ssh_host']}}, {{hostvars['sf-6']['node_ip']}}"
      - "sf-7: {{hostvars['sf-7']['ansible_ssh_host']}}, {{hostvars['sf-7']['node_ip']}}"
      - "sf-8: {{hostvars['sf-8']['ansible_ssh_host']}}, {{hostvars['sf-8']['node_ip']}}"
      - "sf-9: {{hostvars['sf-9']['ansible_ssh_host']}}, {{hostvars['sf-9']['node_ip']}}"
      - "sf-10: {{hostvars['sf-10']['ansible_ssh_host']}}, {{hostvars['sf-10']['node_ip']}}"
