name: Rebuild CI dependencies

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Rebuild CI images"]
    types: [completed]
  schedule:
    - cron: '00 00 * * *'        # utc


env:
  http_proxy: http://192.168.1.15:3128
  https_proxy: http://192.168.1.15:3128
  PIP_INDEX_URL: https://devpi.home.stillhq.com/root/pypi/+simple/

jobs:
  ci-dependencies:
    # Skip if triggered by a failed image build
    if: >-
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: [self-hosted, vm, debian-12]
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout the actions repository
        uses: actions/checkout@v6
        with:
          repository: shakenfist/actions
          path: actions
          fetch-depth: 0

      - name: Checkout the shakenfist repository
        uses: actions/checkout@v6
        with:
          path: shakenfist
          fetch-depth: 1

      - name: Install the github command line
        run: |
          sudo apt update
          sudo apt install -y curl

          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

          sudo apt update
          sudo apt install -y gh

      - name: Lookup latest version of the GitHub actions runner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          actions_url=$(gh release view --repo actions/runner --json assets | \
              jq -r '.assets[].url | select (contains("linux-x64-2")) | select (test("[0-9].tar.gz$"))')
          echo "GITHUB_ACTIONS_URL=$actions_url" >> $GITHUB_ENV

      - name: Build dependencies image
        env:
          GITLAB_TESTDATA_TOKEN: ${{ secrets.GITLAB_TESTDATA_TOKEN }}
        run: |
          cd ${GITHUB_WORKSPACE}/actions
          ansible-playbook -i /home/debian/ansible-hosts \
            --extra-vars "identifier=${SHAKENFIST_NAMESPACE} \
              base_image=sf://label/ci-images/debian-12 base_image_user=debian \
              label=ci-images/dependencies actions_url=$GITHUB_ACTIONS_URL \
              gitlab_testdata_token=${GITLAB_TESTDATA_TOKEN}" \
            ansible/ci-dependencies.yml

      - uses: JasonEtco/create-an-issue@v2
        if: failure()
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SF_CI_NAME: ci-dependencies
          SF_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: shakenfist/.github/workflows/ci-images-failure.md
          update_existing: true
          search_existing: open

      - if: failure()
        run: 'echo Created ${{ steps.create-issue.outputs.url }}'