name: Rebuild CI images

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  schedule:
    - cron: '11 0 * * *'        # utc

jobs:
  image_build_matrix:
    name: "${{ matrix.os.name }}"
    strategy:
      fail-fast: false
      matrix:
        os: [
            {
                'name': 'debian-11',
                'baseimage': 'debian:11',
                'baseuser': 'debian',
                'outputlabel': 'ci-images/debian-11',
                'scheduled': True,
                'runs_on': 'debian-11'
            },
            {
                'name': 'debian-12',
                'baseimage': 'debian:12',
                'baseuser': 'debian',
                'outputlabel': 'ci-images/debian-12',
                'scheduled': True,
                'runs_on': 'debian-12'
            },
            {
                'name': 'debian-13',
                'baseimage': 'debian:13',
                'baseuser': 'debian',
                'outputlabel': 'ci-images/debian-13',
                'scheduled': True,
                'runs_on': 'debian-12'
            },
            {
                'name': 'rocky-9',
                'baseimage': 'rocky:9',
                'baseuser': 'cloud-user',
                'outputlabel': 'ci-images/rocky-9',
                'scheduled': True,
                'runs_on': 'debian-11'
            },
            {
                'name': 'rocky-10',
                'baseimage': 'rocky:10',
                'baseuser': 'cloud-user',
                'outputlabel': 'ci-images/rocky-10',
                'scheduled': True,
                'runs_on': 'debian-12'
            },
            {
                'name': 'ubuntu-2004',
                'baseimage': 'ubuntu:20.04',
                'baseuser': 'ubuntu',
                'outputlabel': 'ci-images/ubuntu-2004',
                'scheduled': True,
                'runs_on': 'debian-11'
            },
            {
                'name': 'ubuntu-2204',
                'baseimage': 'ubuntu:22.04',
                'baseuser': 'ubuntu',
                'outputlabel': 'ci-images/ubuntu-2204',
                'scheduled': True,
                'runs_on': 'debian-11'
            },
            {
                'name': 'ubuntu-2404',
                'baseimage': 'ubuntu:24.04',
                'baseuser': 'ubuntu',
                'outputlabel': 'ci-images/ubuntu-2404',
                'scheduled': True,
                'runs_on': 'debian-12'
            },
        ]
    runs-on: [self-hosted, vm, '${{ matrix.os.runs_on }}']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.name }}
      cancel-in-progress: true

    steps:
        - name: Set environment variables
          run: |
            echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

        - name: Checkout the actions repository
          uses: actions/checkout@v6
          with:
            repository: shakenfist/actions
            path: actions
            fetch-depth: 0

        - name: Checkout the shakenfist repository
          uses: actions/checkout@v6
          with:
            repository: shakenfist/shakenfist
            path: shakenfist
            fetch-depth: 2

        - name: Build image
          run: |
            cd ${GITHUB_WORKSPACE}/actions
            ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} \
                base_image=${{ matrix.os.baseimage }} base_image_user=${{ matrix.os.baseuser }} label=${{ matrix.os.outputlabel }}" \
              ansible/ci-image.yml

        - uses: JasonEtco/create-an-issue@v2
          if: failure()
          id: create-issue
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SF_CI_NAME: ${{ matrix.os.name }}
            SF_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          with:
            filename: shakenfist/.github/workflows/ci-images-failure.md
            update_existing: true
            search_existing: open

        - if: failure()
          run: 'echo Created ${{ steps.create-issue.outputs.url }}'
