name: Run automated code formatters

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '13 00 * * *'        # utc
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/code-formatting.yml'


env:
  http_proxy: http://192.168.1.15:3128
  https_proxy: http://192.168.1.15:3128
  PIP_INDEX_URL: https://devpi.home.stillhq.com/root/pypi/+simple/

jobs:
  code-formatters:
    runs-on: [self-hosted, static]
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout the shakenfist repository
        uses: actions/checkout@v6
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Checkout the actions repository
        uses: actions/checkout@v6
        with:
          repository: shakenfist/actions
          path: actions
          fetch-depth: 0

      - name: Install formatting tools in a venv
        run: |
          rm -rf /srv/ci/venv
          python3 -m venv --system-site-packages /srv/ci/venv
          . /srv/ci/venv/bin/activate

          cd ${GITHUB_WORKSPACE}/shakenfist

          pip3 install uv
          uv pip install -r pyproject.toml
          uv pip install pyupgrade reorder-python-imports

      - name: Scan for obsolete syntax
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDENCIES_TOKEN }}
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          . /srv/ci/venv/bin/activate
          ${GITHUB_WORKSPACE}/actions/tools/ci_code_formatting.sh 311
