name: Documentation tests

on:
  pull_request:
    branches:
      - develop
      - v*-releases
    paths:
      - 'docs/**'
      - mkdocs.yml

jobs:
  build-docs:
    runs-on: [self-hosted, static]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Ensure the docs build
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist

          rm -rf ${GITHUB_WORKSPACE}/artifacts/site
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/site

          python3 -mvenv ${GITHUB_WORKSPACE}/tox-venv
          ${GITHUB_WORKSPACE}/tox-venv/bin/pip3 install tox
          ${GITHUB_WORKSPACE}/tox-venv/bin/tox -edocs -- --site-dir ${GITHUB_WORKSPACE}/artifacts/site | tee ${GITHUB_WORKSPACE}/artifacts/site/build.log

          cd ${GITHUB_WORKSPACE}/artifacts
          zip -r ${GITHUB_WORKSPACE}/artifacts/site.zip site

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: site
          retention-days: 90
          if-no-files-found: error
          path: ${GITHUB_WORKSPACE}/artifacts/site.zip