name: Functional tests

# NOTE(mikal): git repos are checked out to /srv/github/_work/{repo}/{repo}
# which is available as GITHUB_WORKSPACE. You can find other environment
# variables at:
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
#
# The can_enqueue / can_merge scheme is as described at:
# https://boinkor.net/2023/11/neat-github-actions-patterns-for-github-merge-queues/

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - develop
      - v*-releases
    paths-ignore:
      - 'docs/**'
      - mkdocs.yml

jobs:
  lint:
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Lint with flake8
        run: |
          /usr/bin/tox -eflake8

  # NOTE(mikal): we need this one early because renovate creates a lot of PRs
  # where the proposed combination of dependencies doesn't actually install and
  # I don't want to waste a lot of CI resources on them.
  requirements_check:
    needs: lint
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-requirements
      cancel-in-progress: true

    steps:
      - name: Checkout shakenfist
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Attempt to install requirements
        run: |
          cd ${GITHUB_WORKSPACE}
          python3 -mvenv venv
          venv/bin/pip3 install -r shakenfist/requirements.txt

  build38:
    needs: [lint, requirements_check]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build38
      cancel-in-progress: true

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run python3 unit tests
        run: |
          /usr/bin/tox -epy3

  functional_matrix_pr:
    if: always() && github.event_name != 'merge_group'
    name: "${{ matrix.os.description }}"
    needs: [lint, requirements_check]
    strategy:
      fail-fast: false
      matrix:
        os: [
          {
            description: 'debian 11 single machine',
            job_name: 'debian-11-localhost',
            base_image: 'sf://label/ci-images/debian-11',
            base_image_user: 'debian',
            topology: 'localhost',
            concurrency: 3
          }
        ]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.job_name }}
      cancel-in-progress: true

    steps:
      - name: Log matrix details
        run: |
          echo "job_name: ${{ matrix.os.job_name }}"
          echo "base_image: ${{ matrix.os.base_image }}"
          echo "base_image_user: ${{ matrix.os.base_image_user }}"
          echo "topology: ${{ matrix.os.topology }}"
          echo "concurrency: ${{ matrix.os.concurrency }}"

      - name: Setup test environment
        uses: shakenfist/actions/setup-test-environment
        with:
          primary_repository: shakenfist/shakenfist

      - name: Build infrastructure
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=${{ matrix.os.base_image }} base_image_user=${{ matrix.os.base_image_user }}" \
              deploy/ansible/ci-topology-${{ matrix.os.topology }}.yml

          if [ "${{ matrix.os.topology }}" == "localhost" ]; then
            echo "UPLOAD_TARGET=10.0.0.10" >> $GITHUB_ENV
          else
            nodes=(10.0.0.20 10.0.0.21 10.0.0.22 10.0.0.23 10.0.0.24)
            random_index=$(( RANDOM % 5 ))
            echo "UPLOAD_TARGET=${nodes[$random_index]}" >> $GITHUB_ENV
          fi

      - name: Log environmental configuration
        run: |
          echo "## ci-environment.sh"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh
          echo
          echo "## Environment variables"
          echo "SF_HEAD_SHA = ${SF_HEAD_SHA}"
          echo "SHAKENFIST_NAMESPACE = ${SHAKENFIST_NAMESPACE}"
          echo "UPLOAD_TARGET = ${UPLOAD_TARGET}"

      - name: Copy CI tools to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp tools \
              ${{ matrix.os.base_image_user }}@${primary}:.

          echo ""
          echo "Copied tools:"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "ls tools"

      - name: Log github actions buffering status
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} python3 tools/buffer.py

      - name: Run getsf installer on primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} /tmp/getsf-wrapper
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              'sudo rm /etc/apache2/sites-enabled/*; sudo a2ensite sf-example.conf; sudo apachectl graceful'

      - name: Wait for API to start answering
        run: |
          set +e

          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} 'sudo chmod ugo+r /etc/sf/* /var/log/syslog'

          count=0
          while [ $count -lt 60 ]
          do
            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} '. /etc/sf/sfrc; sf-client instance list'
            if [ $? == 0 ]; then
              exit 0
            fi

            count=$(( $count + 1 ))
            sleep 5
          done

          exit 1

      - name: Import cached images
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          setup="export PATH=$PATH:/srv/shakenfist/venv/bin;"
          setup="${setup} . /etc/sf/sfrc;"
          setup="${setup} export SHAKENFIST_API_URL=http://localhost:13000;"
          setup="${setup} sf-client artifact upload"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} ubuntu-2004 /srv/ci/ubuntu:20.04 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} debian-11 /srv/ci/debian:11 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} debian-12 /srv/ci/debian:12 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} cirros /srv/ci/cirros --shared"

      - name: Create a base level of activity in the cluster
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              'echo "==== sfrc ===="; cat /etc/sf/sfrc; echo "==== end sfrc ===="'
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              '. /etc/sf/sfrc; for i in `seq 100`; do sf-client --async=continue network create background-$i 10.$i.0.0/24 > /dev/null; echo -n "."; done'
          echo ""

      - name: Make the traces directory
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "sudo mkdir -p /srv/ci/traces; sudo chown -R ${{ matrix.os.base_image_user }}:${{ matrix.os.base_image_user }} /srv/ci/traces"

      - name: Run functional tests
        timeout-minutes: 120
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              $source_path/shakenfist \
              ${{ matrix.os.base_image_user }}@${primary}:shakenfist
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "cd shakenfist/deploy; . /etc/sf/sfrc; sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install -r requirements.txt; set -e; stestr run --concurrency=${{ matrix.os.concurrency}}; stestr slowest"

      - name: Check logs
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_log_checks.sh develop ${{ matrix.os.job_name }}"

      - name: Check SF process CPU usage
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} '. /etc/sf/sfrc; sf-client node cpuhogs -t 0.99'

      - name: Check for reasonable data rates
        timeout-minutes: 5
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_event_checks.sh develop"

      - name: Fetch and tweak inventory
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary}:/etc/sf/inventory.yaml /srv/github/
          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml

          echo "====="
          cat /srv/github/inventory.yaml

      - name: Gather logs
        if: always()
        run: |
          set -x

          # Fetch unit test tracing. Sometimes this isn't present if we failed
          # super early in the CI job.
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          mkdir -p /srv/github/bundle/
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp \
              ${{ matrix.os.base_image_user }}@${primary}:/srv/ci/traces \
              /srv/github/bundle/ || true

          # We need the ssh key in the place ansible expects it to be, which isn't
          # true on the CI worker node.
          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub

          ansible-playbook -i /srv/github/inventory.yaml \
              --extra-vars "base_image_user=${{ matrix.os.base_image_user }} \
              ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-functional-cluster-${{ matrix.os.job_name }}
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

  functional_matrix_merge:
    if: github.event_name == 'merge_group'
    name: "${{ matrix.os.description }}"
    needs: [lint, requirements_check, build38]
    strategy:
      fail-fast: false
      matrix:
        os: [
          {
            description: 'debian 11 single machine',
            job_name: 'debian-11-localhost',
            base_image: 'sf://label/ci-images/debian-11',
            base_image_user: 'debian',
            topology: 'localhost',
            concurrency: 3
          },
          {
            description: 'debian 12 cluster',
            job_name: 'debian-12-slim-primary',
            base_image: 'sf://label/ci-images/debian-12',
            base_image_user: 'debian',
            topology: 'slim-primary',
            concurrency: 5
          },
          {
            description: 'ubuntu 24.04 cluster',
            job_name: 'ubuntu-2404-slim-primary',
            base_image: 'sf://label/ci-images/ubuntu-2404',
            base_image_user: 'ubuntu',
            topology: 'slim-primary',
            concurrency: 5
          },
        ]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.job_name }}
      cancel-in-progress: true

    steps:
      - name: Log matrix details
        run: |
          echo "job_name: ${{ matrix.os.job_name }}"
          echo "base_image: ${{ matrix.os.base_image }}"
          echo "base_image_user: ${{ matrix.os.base_image_user }}"
          echo "topology: ${{ matrix.os.topology }}"
          echo "concurrency: ${{ matrix.os.concurrency }}"

      - name: Setup test environment
        uses: shakenfist/actions/setup-test-environment
        with:
          primary_repository: shakenfist/shakenfist

      - name: Build infrastructure
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=${{ matrix.os.base_image }} base_image_user=${{ matrix.os.base_image_user }}" \
              deploy/ansible/ci-topology-${{ matrix.os.topology }}.yml

          if [ "${{ matrix.os.topology }}" == "localhost" ]; then
            echo "UPLOAD_TARGET=10.0.0.10" >> $GITHUB_ENV
          else
            nodes=(10.0.0.20 10.0.0.21 10.0.0.22 10.0.0.23 10.0.0.24)
            random_index=$(( RANDOM % 5 ))
            echo "UPLOAD_TARGET=${nodes[$random_index]}" >> $GITHUB_ENV
          fi

      - name: Log environmental configuration
        run: |
          echo "## ci-environment.sh"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh
          echo
          echo "## Environment variables"
          echo "SF_HEAD_SHA = ${SF_HEAD_SHA}"
          echo "SHAKENFIST_NAMESPACE = ${SHAKENFIST_NAMESPACE}"
          echo "UPLOAD_TARGET = ${UPLOAD_TARGET}"

      - name: Copy CI tools to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp tools \
              ${{ matrix.os.base_image_user }}@${primary}:.

          echo ""
          echo "Copied tools:"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "ls tools"

      - name: Log github actions buffering status
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} python3 tools/buffer.py

      - name: Run getsf installer on primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} /tmp/getsf-wrapper
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              'sudo rm /etc/apache2/sites-enabled/*; sudo a2ensite sf-example.conf; sudo apachectl graceful'

      - name: Wait for API to start answering
        run: |
          set +e

          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} 'sudo chmod ugo+r /etc/sf/* /var/log/syslog'

          count=0
          while [ $count -lt 60 ]
          do
            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} '. /etc/sf/sfrc; sf-client instance list'
            if [ $? == 0 ]; then
              exit 0
            fi

            count=$(( $count + 1 ))
            sleep 5
          done

          exit 1

      - name: Import cached images
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          setup="export PATH=$PATH:/srv/shakenfist/venv/bin;"
          setup="${setup} . /etc/sf/sfrc;"
          setup="${setup} export SHAKENFIST_API_URL=http://localhost:13000;"
          setup="${setup} sf-client artifact upload"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} ubuntu-2004 /srv/ci/ubuntu:20.04 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} debian-11 /srv/ci/debian:11 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} debian-12 /srv/ci/debian:12 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${UPLOAD_TARGET} \
              "${setup} cirros /srv/ci/cirros --shared"

      - name: Create a base level of activity in the cluster
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              'echo "==== sfrc ===="; cat /etc/sf/sfrc; echo "==== end sfrc ===="'
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              '. /etc/sf/sfrc; for i in `seq 100`; do sf-client --async=continue network create background-$i 10.$i.0.0/24 > /dev/null; echo -n "."; done'
          echo ""

      - name: Make the traces directory
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          script="sudo mkdir -p /srv/ci/traces;"
          script="${script} export USER=\"${{ matrix.os.base_image_user }}\";"
          script="${script} sudo chown -R \${USER}:\${USER} /srv/ci/traces"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "${script}"

      - name: Run functional tests
        timeout-minutes: 180
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${source_path}/shakenfist \
              ${{ matrix.os.base_image_user }}@${primary}:shakenfist

          script="cd shakenfist/deploy/;"
          script="${script} . /etc/sf/sfrc;"
          script="${script} sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install -r requirements.txt;"
          script="${script} set -e;"
          script="${script} stestr run --config cluster-ci.conf --concurrency=${{ matrix.os.concurrency}};"
          script="${script} stestr slowest --config cluster-ci.conf"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} "${script}"

      - name: List failing tests
        if: failure()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          echo "Gathering list of failed tests..."
          touch ${GITHUB_WORKSPACE}/failed
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} \
              "cd shakenfist/deploy; stestr failing --config cluster-ci.conf" > ${GITHUB_WORKSPACE}/failed
          echo

          echo "Failed tests:"
          cat ${GITHUB_WORKSPACE}/failed
          echo

          echo "Searching for matching github issues..."
          failed=$(cat ${GITHUB_WORKSPACE}/failed | grep "FAIL: " | \
                   sed -e 's/FAIL: //' -e 's/shakenfist_ci\.tests\.//')
          for f in ${failed}; do
              echo "Test ${f} failed"
              gh search issues --state=open "Failure in CI: ${f}"
              echo
          done

      - name: Check logs
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_log_checks.sh develop ${{ matrix.os.job_name }}"

      - name: Check SF process CPU usage
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary} '. /etc/sf/sfrc; sf-client node cpuhogs -t 0.99'

      - name: Check for reasonable data rates
        timeout-minutes: 5
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_event_checks.sh develop"

      - name: Fetch and tweak inventory
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ matrix.os.base_image_user }}@${primary}:/etc/sf/inventory.yaml /srv/github/
          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml

          echo "====="
          cat /srv/github/inventory.yaml

      - name: Gather logs
        if: always()
        run: |
          set -x

          # Fetch unit test tracing. Sometimes this isn't present if we failed
          # super early in the CI job.
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          mkdir -p /srv/github/bundle/
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp \
              ${{ matrix.os.base_image_user }}@${primary}:/srv/ci/traces \
              /srv/github/bundle/ || true

          # We need the ssh key in the place ansible expects it to be, which isn't
          # true on the CI worker node.
          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub

          ansible-playbook -i /srv/github/inventory.yaml \
              --extra-vars "base_image_user=${{ matrix.os.base_image_user }} \
              ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-functional-cluster-${{ matrix.os.job_name }}
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

  ansible_modules:
    if: github.event_name == 'merge_group'
    needs: [lint, requirements_check, build38]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ansiblemodules
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SF_PRIMARY_REPO=$( echo ${{ github.repository }} | cut -f 2 -d '/' )" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout shakenfist
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Determine if there is any dependency between the repositories
        run: |
          python3 ${GITHUB_WORKSPACE}/shakenfist/tools/clone_with_depends.py

      - name: Build infrastructure
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=sf://label/ci-images/debian-11 base_image_user=debian" \
              deploy/ansible/ci-topology-slim-primary.yml

          nodes=(10.0.0.20 10.0.0.21 10.0.0.22 10.0.0.23 10.0.0.24)
          random_index=$(( RANDOM % 5 ))
          echo "UPLOAD_TARGET=${nodes[$random_index]}" >> $GITHUB_ENV

      - name: Log environmental configuration
        run: |
          echo "## ci-environment.sh"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh
          echo
          echo "## Environment variables"
          echo "SF_HEAD_SHA = ${SF_HEAD_SHA}"
          echo "SHAKENFIST_NAMESPACE = ${SHAKENFIST_NAMESPACE}"
          echo "UPLOAD_TARGET = ${UPLOAD_TARGET}"

      - name: Copy CI tools to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp tools \
              debian@$primary:.

      - name: Run getsf installer on primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary /tmp/getsf-wrapper
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary \
              'sudo rm /etc/apache2/sites-enabled/*; sudo a2ensite sf-example.conf; sudo apachectl graceful'

      - name: Wait for API to start answering
        run: |
          set +e

          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary 'sudo chmod ugo+r /etc/sf/* /var/log/syslog'

          count=0
          while [ $count -lt 60 ]
          do
            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary '. /etc/sf/sfrc; sf-client instance list'
            if [ $? == 0 ]; then
              exit 0
            fi

            count=$(( $count + 1 ))
            sleep 5
          done

          exit 1

      - name: Import cached images
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          setup="export PATH=$PATH:/srv/shakenfist/venv/bin;"
          setup="${setup} . /etc/sf/sfrc;"
          setup="${setup} export SHAKENFIST_API_URL=http://localhost:13000;"
          setup="${setup} sf-client artifact upload"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@${UPLOAD_TARGET} \
              "${setup} ubuntu-2004 /srv/ci/ubuntu:20.04 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@${UPLOAD_TARGET} \
              "${setup} debian-11 /srv/ci/debian:11 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@${UPLOAD_TARGET} \
              "${setup} debian-12 /srv/ci/debian:12 --shared --no-checksum"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@${UPLOAD_TARGET} \
              "${setup} cirros /srv/ci/cirros --shared"

      - name: Run ansible module tests
        timeout-minutes: 60
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              $source_path/shakenfist \
              debian@$primary:shakenfist
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary "cd shakenfist/deploy; . /etc/sf/sfrc; bash ansiblemoduletests.sh"

      - name: Check logs
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_log_checks.sh develop ansible-modules"

      - name: Check process CPU usage
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary '. /etc/sf/sfrc; sf-client node cpuhogs -t 0.99'

      - name: Check for reasonable data rates
        timeout-minutes: 5
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_event_checks.sh develop"

      - name: Fetch and tweak inventory
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary:/etc/sf/inventory.yaml /srv/github/
          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml

          echo "====="
          cat /srv/github/inventory.yaml

      - name: Gather logs
        if: always()
        run: |
          set -x

          # We need the ssh key in the place ansible expects it to be, which isn't
          # true on the CI worker node.
          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub
          chown -R debian.debian /home/debian/.ssh

          ansible-playbook -i /srv/github/inventory.yaml \
              --extra-vars "base_image_user=debian ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-functional-ansible-modules
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

  node_lifecycle:
    if: github.event_name == 'merge_group'
    needs: [lint, requirements_check, build38]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-nodelifecycle
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SF_PRIMARY_REPO=$( echo ${{ github.repository }} | cut -f 2 -d '/' )" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout shakenfist
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Determine if there is any dependency between the repositories
        run: |
          python3 ${GITHUB_WORKSPACE}/shakenfist/tools/clone_with_depends.py

      - name: Build infrastructure
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=sf://label/ci-images/debian-11 base_image_user=debian" \
              deploy/ansible/ci-topology-slim-primary.yml

          nodes=(10.0.0.20 10.0.0.21 10.0.0.22 10.0.0.23 10.0.0.24)
          random_index=$(( RANDOM % 5 ))
          echo "UPLOAD_TARGET=${nodes[$random_index]}" >> $GITHUB_ENV

      - name: Log environmental configuration
        run: |
          echo "## ci-environment.sh"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh
          echo
          echo "## Environment variables"
          echo "SF_HEAD_SHA = ${SF_HEAD_SHA}"
          echo "SHAKENFIST_NAMESPACE = ${SHAKENFIST_NAMESPACE}"
          echo "UPLOAD_TARGET = ${UPLOAD_TARGET}"

      - name: Copy CI tools to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp tools \
              debian@$primary:.

      - name: Run getsf installer on primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary /tmp/getsf-wrapper
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary \
              'sudo rm /etc/apache2/sites-enabled/*; sudo a2ensite sf-example.conf; sudo apachectl graceful'

      - name: Wait for API to start answering
        run: |
          set +e

          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary 'sudo chmod ugo+r /etc/sf/* /var/log/syslog'

          count=0
          while [ $count -lt 60 ]
          do
            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary '. /etc/sf/sfrc; sf-client instance list'
            if [ $? == 0 ]; then
              exit 0
            fi

            count=$(( $count + 1 ))
            sleep 5
          done

          exit 1

      - name: Import cached images
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          setup="export PATH=$PATH:/srv/shakenfist/venv/bin;"
          setup="${setup} . /etc/sf/sfrc;"
          setup="${setup} export SHAKENFIST_API_URL=http://localhost:13000;"
          setup="${setup} sf-client artifact upload"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@${UPLOAD_TARGET} \
              "${setup} debian-11 /srv/ci/debian:11 --shared --no-checksum"

      - name: Run node lifecycle tests
        timeout-minutes: 60
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              $source_path/shakenfist \
              debian@$primary:shakenfist
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary "cd shakenfist/deploy; . /etc/sf/sfrc; bash nodelifecycletests.sh"

      - name: Check logs
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_log_checks.sh develop node-lifecycle"

      - name: Restart Shaken Fist nodes so we can collect logs
        if: always()
        run: |
          set -x
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          for node in ${sf1_uuid} ${sf2_uuid} ${sf3_uuid} ${sf4_uuid} ${sf5_uuid}; do
              sf-client instance reboot --hard ${node}
          done
          sleep 90

      - name: Check for reasonable data rates
        timeout-minutes: 5
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_event_checks.sh develop"

      - name: Fetch and tweak inventory
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary:/etc/sf/inventory.yaml /srv/github/
          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml

          echo "====="
          cat /srv/github/inventory.yaml

      - name: Gather logs
        if: always()
        run: |
          set -x

          # We need the ssh key in the place ansible expects it to be, which isn't
          # true on the CI worker node.
          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub
          chown -R debian.debian /home/debian/.ssh

          ansible-playbook -i /srv/github/inventory.yaml \
              --extra-vars "base_image_user=debian ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-functional-node-lifecycle
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

  upgrade_0_6_15:
    if: github.event_name == 'merge_group'
    needs: [lint, requirements_check, build38]
    runs-on: [self-hosted, vm]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-upgrade-0-6-15
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SF_PRIMARY_REPO=$( echo ${{ github.repository }} | cut -f 2 -d '/' )" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout shakenfist
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Determine if there is any dependency between the repositories
        run: |
          python3 ${GITHUB_WORKSPACE}/shakenfist/tools/clone_with_depends.py

      - name: Build infrastructure
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=sf://label/ci-images/debian-11 base_image_user=debian" \
              deploy/ansible/ci-topology-localhost-upgrade.yml

          echo "UPLOAD_TARGET=10.0.0.10" >> $GITHUB_ENV

      - name: Log environmental configuration
        run: |
          echo "## ci-environment.sh"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh
          echo
          echo "## Environment variables"
          echo "SF_HEAD_SHA = ${SF_HEAD_SHA}"
          echo "SHAKENFIST_NAMESPACE = ${SHAKENFIST_NAMESPACE}"
          echo "UPLOAD_TARGET = ${UPLOAD_TARGET}"

      - name: Copy CI tools to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp tools \
              debian@$primary:.

      - name: Run getsf to only install etcd, and then restore a backup
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary /tmp/getsf-wrapper --tags bootstrap,etcd

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary 'sudo chmod ugo+r /etc/sf/*; . /etc/sf/sfrc; /srv/shakenfist/venv/bin/sf-backup restore /srv/ci/backup-0.6.15-20230319'

      - name: Run getsf installer on primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary /tmp/getsf-wrapper
          echo ""
          echo ""
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary \
              'sudo rm /etc/apache2/sites-enabled/*; sudo a2ensite sf-example.conf; sudo apachectl graceful'
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary 'sudo chmod ugo+r /etc/sf/*'

      # The sf-backup script deliberately clobbers keys in its output, so we need
      # to repair the system key before we can use command line tools.
      - name: Repair clobbered system key
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary '. /etc/sf/sfrc; /srv/shakenfist/venv/bin/sf-ctl bootstrap-system-key deploy ${SHAKENFIST_KEY}'

      - name: List current nodes
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@$primary '. /etc/sf/sfrc; sf-client node list'

      - name: Wait for five minutes
        run: sleep 300

      - name: Check logs
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_log_checks.sh develop upgrade-0-6-15"

      - name: Check for reasonable data rates
        timeout-minutes: 5
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}/shakenfist
          tools/run_remote ${primary} "sudo bash tools/ci_event_checks.sh develop"

      - name: Fetch and tweak inventory
        if: always()
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              debian@$primary:/etc/sf/inventory.yaml /srv/github/
          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml

          echo "====="
          cat /srv/github/inventory.yaml

      - name: Gather logs
        if: always()
        run: |
          set -x

          # We need the ssh key in the place ansible expects it to be, which isn't
          # true on the CI worker node.
          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub

          ansible-playbook -i /srv/github/inventory.yaml \
              --extra-vars "base_image_user=debian ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-functional-upgrade-0-6-15
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

  can_see_status:
    runs-on: ubuntu-latest
    steps:
      - name: "Immediate success"
        run: true

  can_enqueue:
    needs:
      - lint
      - build38
      - requirements_check
      - functional_matrix_pr
    if: always() && github.event_name != 'merge_group'
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
    - env:
        NEEDS_JSON: "${{toJSON(needs)}}"
      name: Transform outcomes
      run: |
        echo "ALL_SUCCESS=$(echo "$NEEDS_JSON" | jq '. | to_entries | map([.value.result == "success", .value.result == "skipped"] | any) | all')" >>$GITHUB_ENV
    - name: Check outcomes
      run: "[ $ALL_SUCCESS == true ]"

  can_merge:
    needs:
      - lint
      - build38
      - requirements_check
      - functional_matrix_merge
      - ansible_modules
      - node_lifecycle
      - upgrade_0_6_15
    if: always() && github.event_name == 'merge_group'
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
    - env:
        NEEDS_JSON: "${{toJSON(needs)}}"
      name: Transform outcomes
      run: |
        echo "ALL_SUCCESS=$(echo "$NEEDS_JSON" | jq '. | to_entries | map([.value.result == "success", .value.result == "skipped"] | any) | all')" >>$GITHUB_ENV
    - name: Check outcomes
      run: "[ $ALL_SUCCESS == true ]"