name: Sync docs from affiliated projects for web publication

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'        # utc

jobs:
  docs-sync:
    runs-on: [self-hosted, static]
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout the shakenfist repository
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Checkout the actions repository
        uses: actions/checkout@v4
        with:
          repository: shakenfist/actions
          path: actions
          fetch-depth: 0

      - name: Checkout the kerbside repository
        uses: actions/checkout@v4
        with:
          repository: shakenfist/kerbside
          path: kerbside
          fetch-depth: 0

      - name: Import docs from other repositories
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDENCIES_TOKEN }}
        run: |
          ${GITHUB_WORKSPACE}/actions/tools/ci_sync_docs.sh
